/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author User
 */
public class adminBranchNetworks extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(adminBranchNetworks.class.getName());

    /**
     * Creates new form AdminOrderEdit
     */
    public adminBranchNetworks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutbutton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        ManageUserButton = new javax.swing.JButton();
        workLoadButton = new javax.swing.JButton();
        MyProfileButton = new javax.swing.JButton();
        Dashboardbutton = new javax.swing.JButton();
        branchAndNetworksButton = new javax.swing.JButton();
        ManageOrderButton = new javax.swing.JButton();
        PriceConfigurationButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        employeeIdTextF = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        Topbar = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        role = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TotalOrdersLabel = new javax.swing.JLabel();
        TotalOrderNumbers = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        TotalEmployeesLabel = new javax.swing.JLabel();
        TotalEmployeesNumber = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        editButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        BranchDetailsLabel = new javax.swing.JLabel();
        branchIDlabel = new javax.swing.JLabel();
        BranchNameLabel = new javax.swing.JLabel();
        BranchEmailLabel = new javax.swing.JLabel();
        branchNumberLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        branchIDtextF = new javax.swing.JTextField();
        BranchNametextF = new javax.swing.JTextField();
        branchEmailTextF = new javax.swing.JTextField();
        BranchNumberTextF = new javax.swing.JTextField();
        BranchAddressTextF = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1050, 600));
        getContentPane().setLayout(null);

        logoutbutton.setBackground(new java.awt.Color(33, 38, 49));
        logoutbutton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        logoutbutton.setForeground(new java.awt.Color(239, 68, 68));
        logoutbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        logoutbutton.setText("Logout");
        logoutbutton.setPreferredSize(new java.awt.Dimension(148, 50));
        getContentPane().add(logoutbutton);
        logoutbutton.setBounds(14, 544, 160, 50);

        jPanel3.setBackground(new java.awt.Color(33, 38, 49));
        jPanel3.setLayout(null);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(0, 531, 190, 10);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(0, 76, 190, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(99, 47));
        jPanel3.add(jLabel1);
        jLabel1.setBounds(20, 10, 169, 64);

        ManageUserButton.setBackground(new java.awt.Color(33, 38, 49));
        ManageUserButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        ManageUserButton.setForeground(new java.awt.Color(255, 255, 255));
        ManageUserButton.setText("Manage User");
        jPanel3.add(ManageUserButton);
        ManageUserButton.setBounds(10, 150, 170, 50);

        workLoadButton.setBackground(new java.awt.Color(33, 38, 49));
        workLoadButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        workLoadButton.setForeground(new java.awt.Color(255, 255, 255));
        workLoadButton.setText("Workload");
        jPanel3.add(workLoadButton);
        workLoadButton.setBounds(10, 210, 170, 50);

        MyProfileButton.setBackground(new java.awt.Color(33, 38, 49));
        MyProfileButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        MyProfileButton.setForeground(new java.awt.Color(255, 255, 255));
        MyProfileButton.setText("My Profile");
        MyProfileButton.addActionListener(this::MyProfileButtonActionPerformed);
        jPanel3.add(MyProfileButton);
        MyProfileButton.setBounds(10, 450, 170, 50);

        Dashboardbutton.setBackground(new java.awt.Color(33, 38, 49));
        Dashboardbutton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        Dashboardbutton.setForeground(new java.awt.Color(255, 255, 255));
        Dashboardbutton.setText("Dashboard");
        jPanel3.add(Dashboardbutton);
        Dashboardbutton.setBounds(10, 90, 170, 50);

        branchAndNetworksButton.setBackground(new java.awt.Color(216, 140, 81));
        branchAndNetworksButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        branchAndNetworksButton.setForeground(new java.awt.Color(255, 255, 255));
        branchAndNetworksButton.setText("Branch and Network");
        branchAndNetworksButton.setPreferredSize(new java.awt.Dimension(99, 27));
        branchAndNetworksButton.addActionListener(this::branchAndNetworksButtonActionPerformed);
        jPanel3.add(branchAndNetworksButton);
        branchAndNetworksButton.setBounds(10, 270, 170, 50);

        ManageOrderButton.setBackground(new java.awt.Color(33, 38, 49));
        ManageOrderButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        ManageOrderButton.setForeground(new java.awt.Color(255, 255, 255));
        ManageOrderButton.setText("Manage Order");
        jPanel3.add(ManageOrderButton);
        ManageOrderButton.setBounds(10, 330, 170, 50);

        PriceConfigurationButton.setBackground(new java.awt.Color(33, 38, 49));
        PriceConfigurationButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        PriceConfigurationButton.setForeground(new java.awt.Color(255, 255, 255));
        PriceConfigurationButton.setText("Price Configuration");
        jPanel3.add(PriceConfigurationButton);
        PriceConfigurationButton.setBounds(10, 390, 170, 50);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 200, 600);

        jPanel2.setBackground(new java.awt.Color(238, 233, 223));
        jPanel2.setLayout(null);

        employeeIdTextF.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        employeeIdTextF.setText("#Enter Employee ID");
        employeeIdTextF.setPreferredSize(new java.awt.Dimension(626, 65));
        employeeIdTextF.addActionListener(this::employeeIdTextFActionPerformed);
        jPanel2.add(employeeIdTextF);
        employeeIdTextF.setBounds(260, 150, 420, 46);

        searchButton.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        searchButton.setText("Search");
        jPanel2.add(searchButton);
        searchButton.setBounds(700, 150, 94, 46);

        Topbar.setLayout(null);

        name.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        name.setText("Name");
        Topbar.add(name);
        name.setBounds(770, 10, 100, 22);

        role.setText("Role");
        Topbar.add(role);
        role.setBounds(770, 40, 90, 16);

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pfp.jpg"))); // NOI18N
        Topbar.add(profile);
        profile.setBounds(700, 6, 60, 60);

        jPanel2.add(Topbar);
        Topbar.setBounds(180, 0, 870, 70);

        jPanel1.setLayout(null);

        TotalOrdersLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TotalOrdersLabel.setText("Total Orders");
        jPanel1.add(TotalOrdersLabel);
        TotalOrdersLabel.setBounds(40, 10, 90, 20);

        TotalOrderNumbers.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TotalOrderNumbers.setText("100");
        jPanel1.add(TotalOrderNumbers);
        TotalOrderNumbers.setBounds(60, 30, 80, 32);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(260, 240, 160, 70);

        jPanel6.setLayout(null);

        TotalEmployeesLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TotalEmployeesLabel.setText("Total Employees");
        jPanel6.add(TotalEmployeesLabel);
        TotalEmployeesLabel.setBounds(20, 10, 130, 20);

        TotalEmployeesNumber.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TotalEmployeesNumber.setText("20");
        jPanel6.add(TotalEmployeesNumber);
        TotalEmployeesNumber.setBounds(70, 30, 70, 32);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(490, 240, 160, 70);

        jPanel4.setLayout(null);

        editButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editButton.setText("Edit");
        jPanel4.add(editButton);
        editButton.setBounds(620, 10, 100, 40);

        saveButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveButton.setText("Save");
        jPanel4.add(saveButton);
        saveButton.setBounds(620, 200, 100, 40);

        BranchDetailsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BranchDetailsLabel.setText("Branch Details");
        jPanel4.add(BranchDetailsLabel);
        BranchDetailsLabel.setBounds(20, 0, 190, 40);

        branchIDlabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        branchIDlabel.setText("Branch ID");
        jPanel4.add(branchIDlabel);
        branchIDlabel.setBounds(50, 40, 130, 30);

        BranchNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BranchNameLabel.setText("Branch Name");
        jPanel4.add(BranchNameLabel);
        BranchNameLabel.setBounds(50, 80, 130, 30);

        BranchEmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BranchEmailLabel.setText("Branch Email");
        jPanel4.add(BranchEmailLabel);
        BranchEmailLabel.setBounds(50, 120, 110, 30);

        branchNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        branchNumberLabel.setText("Branch Number");
        jPanel4.add(branchNumberLabel);
        branchNumberLabel.setBounds(50, 160, 110, 30);

        addressLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressLabel.setText("Address");
        jPanel4.add(addressLabel);
        addressLabel.setBounds(50, 196, 110, 30);

        branchIDtextF.setText("#250455");
        jPanel4.add(branchIDtextF);
        branchIDtextF.setBounds(260, 40, 260, 30);

        BranchNametextF.setText("Hamro Doko Kathmandu");
        jPanel4.add(BranchNametextF);
        BranchNametextF.setBounds(260, 80, 260, 30);

        branchEmailTextF.setText("xyz@gmail.com");
        jPanel4.add(branchEmailTextF);
        branchEmailTextF.setBounds(260, 120, 260, 30);

        BranchNumberTextF.setText("9876543210");
        jPanel4.add(BranchNumberTextF);
        BranchNumberTextF.setBounds(260, 162, 260, 30);

        BranchAddressTextF.setText("Kathmandu, Nepal");
        jPanel4.add(BranchAddressTextF);
        BranchAddressTextF.setBounds(260, 202, 260, 30);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(270, 330, 730, 250);

        createButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createButton.setText("Create +");
        jPanel2.add(createButton);
        createButton.setBounds(860, 150, 120, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1050, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void branchAndNetworksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchAndNetworksButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branchAndNetworksButtonActionPerformed

    private void employeeIdTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeIdTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeIdTextFActionPerformed

    private void MyProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyProfileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MyProfileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new adminBranchNetworks().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BranchAddressTextF;
    private javax.swing.JLabel BranchDetailsLabel;
    private javax.swing.JLabel BranchEmailLabel;
    private javax.swing.JLabel BranchNameLabel;
    private javax.swing.JTextField BranchNametextF;
    private javax.swing.JTextField BranchNumberTextF;
    private javax.swing.JButton Dashboardbutton;
    private javax.swing.JButton ManageOrderButton;
    private javax.swing.JButton ManageUserButton;
    private javax.swing.JButton MyProfileButton;
    private javax.swing.JButton PriceConfigurationButton;
    private javax.swing.JPanel Topbar;
    private javax.swing.JLabel TotalEmployeesLabel;
    private javax.swing.JLabel TotalEmployeesNumber;
    private javax.swing.JLabel TotalOrderNumbers;
    private javax.swing.JLabel TotalOrdersLabel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton branchAndNetworksButton;
    private javax.swing.JTextField branchEmailTextF;
    private javax.swing.JLabel branchIDlabel;
    private javax.swing.JTextField branchIDtextF;
    private javax.swing.JLabel branchNumberLabel;
    private javax.swing.JButton createButton;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField employeeIdTextF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JLabel name;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel role;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton workLoadButton;
    // End of variables declaration//GEN-END:variables
// =========================================================================
    // TOP BAR & SEARCH INPUT
    // =========================================================================

    public void setTopBar(String userName, String userRole) {
        name.setText(userName);
        role.setText(userRole);
    }

    public String getSearchInput() {
        return employeeIdTextF.getText().trim(); // This is the search bar at the top!
    }

    // =========================================================================
    // DATA INJECTION & LOCKING
    // =========================================================================

    public void setBranchStats(String totalOrders, String totalEmployees) {
        TotalOrdersLabel.setText(totalOrders);
        TotalEmployeesLabel.setText(totalEmployees);
    }

    public void setBranchDetails(String id, String branchName, String email, String phone, String address) {
        branchIDtextF.setText(id); 
        BranchNametextF.setText(branchName);
        branchEmailTextF.setText(email);
        BranchNumberTextF.setText(phone);
        BranchAddressTextF.setText(address); 
    }

    public void setFormState(String state) {
        if (state.equals("VIEW")) {
            // Locked - User just searched
            branchIDtextF.setEditable(false);
            BranchNametextF.setEditable(false);
            branchEmailTextF.setEditable(false);
            BranchNumberTextF.setEditable(false);
            BranchAddressTextF.setEditable(false);
            
            saveButton.setEnabled(false);
            editButton.setEnabled(true);
            
        } else if (state.equals("EDIT")) {
            // Unlocked - User clicked Edit (ID is always locked!)
            branchIDtextF.setEditable(false);
            BranchNametextF.setEditable(true);
            branchEmailTextF.setEditable(true);
            BranchNumberTextF.setEditable(true);
            BranchAddressTextF.setEditable(true);
            
            saveButton.setEnabled(true);
            editButton.setEnabled(false);
            
        } else if (state.equals("CREATE")) {
            // Completely wiped clean to type a new branch!
            setBranchDetails("AUTO", "", "", "", "");
            setBranchStats("0", "0"); // New branches have no stats yet
            
            branchIDtextF.setEditable(false); // ID is generated by database
            BranchNametextF.setEditable(true);
            branchEmailTextF.setEditable(true);
            BranchNumberTextF.setEditable(true);
            BranchAddressTextF.setEditable(true);
            
            saveButton.setEnabled(true);
            editButton.setEnabled(false);
        }
    }

    // Grab updated/new data for the database
    public String getBranchNameInput() { return BranchNametextF.getText().trim(); }
    public String getBranchEmailInput() { return branchEmailTextF.getText().trim(); }
    public String getBranchPhoneInput() { return BranchNumberTextF.getText().trim(); }
    public String getBranchAddressInput() { return BranchAddressTextF.getText().trim(); }

    // =========================================================================
    // BUTTON LISTENERS
    // =========================================================================
    
    public void addSearchListener(java.awt.event.ActionListener listener) { searchButton.addActionListener(listener); }
    public void addEditListener(java.awt.event.ActionListener listener) { editButton.addActionListener(listener); }
    public void addSaveListener(java.awt.event.ActionListener listener) { saveButton.addActionListener(listener); }
    public void addCreateListener(java.awt.event.ActionListener listener) { createButton.addActionListener(listener); }
    
    // Navigators
    public void addDashboardListener(java.awt.event.ActionListener listener) { Dashboardbutton.addActionListener(listener); }
    public void addLogoutListener(java.awt.event.ActionListener listener) { logoutbutton.addActionListener(listener); }
}
