/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Acer
 */
public class branchlocationmgmt extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(branchlocationmgmt.class.getName());

    /**
     * Creates new form Employee_Dashboard
     */
    public branchlocationmgmt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Sidebar = new javax.swing.JPanel();
        dashboard = new javax.swing.JButton();
        manageUsers = new javax.swing.JButton();
        WorkLoad = new javax.swing.JButton();
        BranchAndNetworks = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        ManageOrders = new javax.swing.JButton();
        PriceConfiguration = new javax.swing.JButton();
        MyProfile = new javax.swing.JButton();
        DokoImage = new javax.swing.JLabel();
        Topbar = new javax.swing.JPanel();
        profile = new javax.swing.JLabel();
        Profile = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BranchDetailsPanel = new javax.swing.JPanel();
        branchID = new javax.swing.JLabel();
        branchName = new javax.swing.JLabel();
        branchEmail = new javax.swing.JLabel();
        phoneNumberBranch = new javax.swing.JLabel();
        AddressReceiver = new javax.swing.JLabel();
        BranchIDT = new javax.swing.JTextField();
        BranchNameT = new javax.swing.JTextField();
        EmailT = new javax.swing.JTextField();
        BranchPhoneNumberT = new javax.swing.JTextField();
        ReceiverAddressT = new javax.swing.JTextField();
        BranchDetailsLabel = new javax.swing.JLabel();
        Edit = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        EnterBrannchID = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Create = new javax.swing.JButton();
        totalOrdersUP = new javax.swing.JLabel();
        TotalEmployeesUP = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        totalEmployee = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        TotalOrders = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Dashboard");
        setBackground(new java.awt.Color(238, 233, 223));
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(238, 233, 223));
        MainPanel.setPreferredSize(new java.awt.Dimension(1050, 600));
        MainPanel.setLayout(null);

        Sidebar.setBackground(new java.awt.Color(33, 38, 49));
        Sidebar.setLayout(null);

        dashboard.setBackground(new java.awt.Color(33, 38, 49));
        dashboard.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setText("Dashboard");
        Sidebar.add(dashboard);
        dashboard.setBounds(6, 86, 168, 50);

        manageUsers.setBackground(new java.awt.Color(33, 38, 49));
        manageUsers.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        manageUsers.setForeground(new java.awt.Color(255, 255, 255));
        manageUsers.setText("Manage Users");
        Sidebar.add(manageUsers);
        manageUsers.setBounds(6, 153, 168, 50);

        WorkLoad.setBackground(new java.awt.Color(216, 140, 81));
        WorkLoad.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        WorkLoad.setForeground(new java.awt.Color(255, 255, 255));
        WorkLoad.setText("Workload");
        Sidebar.add(WorkLoad);
        WorkLoad.setBounds(6, 214, 168, 50);

        BranchAndNetworks.setBackground(new java.awt.Color(33, 38, 49));
        BranchAndNetworks.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        BranchAndNetworks.setForeground(new java.awt.Color(255, 255, 255));
        BranchAndNetworks.setText("Branch and Networks");
        Sidebar.add(BranchAndNetworks);
        BranchAndNetworks.setBounds(6, 281, 168, 50);

        logout.setBackground(new java.awt.Color(33, 38, 49));
        logout.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 0, 51));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        logout.setText("Logout");
        Sidebar.add(logout);
        logout.setBounds(6, 541, 168, 53);
        Sidebar.add(jSeparator1);
        jSeparator1.setBounds(0, 532, 180, 3);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        Sidebar.add(jLabel1);
        jLabel1.setBounds(180, 541, 0, 53);
        Sidebar.add(jSeparator2);
        jSeparator2.setBounds(0, 69, 180, 10);

        ManageOrders.setBackground(new java.awt.Color(33, 38, 49));
        ManageOrders.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        ManageOrders.setForeground(new java.awt.Color(255, 255, 255));
        ManageOrders.setText("Manage Orders");
        ManageOrders.addActionListener(this::ManageOrdersActionPerformed);
        Sidebar.add(ManageOrders);
        ManageOrders.setBounds(10, 340, 160, 45);

        PriceConfiguration.setBackground(new java.awt.Color(33, 38, 49));
        PriceConfiguration.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        PriceConfiguration.setForeground(new java.awt.Color(255, 255, 255));
        PriceConfiguration.setText("Price Configuration");
        Sidebar.add(PriceConfiguration);
        PriceConfiguration.setBounds(6, 394, 168, 45);

        MyProfile.setBackground(new java.awt.Color(33, 38, 49));
        MyProfile.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        MyProfile.setForeground(new java.awt.Color(255, 255, 255));
        MyProfile.setText("My Profile");
        Sidebar.add(MyProfile);
        MyProfile.setBounds(6, 451, 168, 45);

        DokoImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\sharm\\OneDrive\\Desktop\\testDoko\\group-5-test-doko\\src\\dokotest\\logo.png")); // NOI18N
        DokoImage.setText("jLabel2");
        Sidebar.add(DokoImage);
        DokoImage.setBounds(10, 0, 160, 70);

        MainPanel.add(Sidebar);
        Sidebar.setBounds(0, 0, 180, 600);

        Topbar.setLayout(null);

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profile.png"))); // NOI18N
        Topbar.add(profile);
        profile.setBounds(757, 0, 0, 82);

        Profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile.png"))); // NOI18N
        Topbar.add(Profile);
        Profile.setBounds(670, 0, 84, 82);

        jLabel9.setText("Username");
        Topbar.add(jLabel9);
        jLabel9.setBounds(760, 10, 90, 30);

        jLabel10.setText("Role");
        Topbar.add(jLabel10);
        jLabel10.setBounds(760, 50, 43, 16);

        MainPanel.add(Topbar);
        Topbar.setBounds(186, 0, 0, 0);

        BranchDetailsPanel.setLayout(null);

        branchID.setText("Branch ID");
        BranchDetailsPanel.add(branchID);
        branchID.setBounds(68, 66, 79, 16);

        branchName.setText("Branch Name");
        BranchDetailsPanel.add(branchName);
        branchName.setBounds(68, 125, 90, 16);

        branchEmail.setText("Branch Email");
        BranchDetailsPanel.add(branchEmail);
        branchEmail.setBounds(68, 180, 90, 16);

        phoneNumberBranch.setText("Branch Phone Number");
        BranchDetailsPanel.add(phoneNumberBranch);
        phoneNumberBranch.setBounds(68, 235, 120, 16);

        AddressReceiver.setText("Receiver's Address");
        BranchDetailsPanel.add(AddressReceiver);
        AddressReceiver.setBounds(68, 286, 100, 16);

        BranchIDT.setText("#2345");
        BranchIDT.addActionListener(this::BranchIDTActionPerformed);
        BranchDetailsPanel.add(BranchIDT);
        BranchIDT.setBounds(210, 60, 147, 31);

        BranchNameT.setText("Dillibazar");
        BranchNameT.addActionListener(this::BranchNameTActionPerformed);
        BranchDetailsPanel.add(BranchNameT);
        BranchNameT.setBounds(210, 120, 147, 31);

        EmailT.setText("dillibazar22@gmail.com");
        BranchDetailsPanel.add(EmailT);
        EmailT.setBounds(210, 180, 147, 30);

        BranchPhoneNumberT.setText("9800000000");
        BranchPhoneNumberT.addActionListener(this::BranchPhoneNumberTActionPerformed);
        BranchDetailsPanel.add(BranchPhoneNumberT);
        BranchPhoneNumberT.setBounds(210, 230, 146, 30);

        ReceiverAddressT.setText("Kapan");
        BranchDetailsPanel.add(ReceiverAddressT);
        ReceiverAddressT.setBounds(210, 280, 146, 30);

        BranchDetailsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BranchDetailsLabel.setText("Branch Details");
        BranchDetailsPanel.add(BranchDetailsLabel);
        BranchDetailsLabel.setBounds(0, 0, 120, 33);

        Edit.setBackground(new java.awt.Color(168, 168, 168));
        Edit.setText("Edit");
        Edit.addActionListener(this::EditActionPerformed);
        BranchDetailsPanel.add(Edit);
        Edit.setBounds(620, 8, 99, 35);

        Save.setBackground(new java.awt.Color(168, 168, 168));
        Save.setText("Save");
        Save.addActionListener(this::SaveActionPerformed);
        BranchDetailsPanel.add(Save);
        Save.setBounds(620, 330, 99, 35);

        MainPanel.add(BranchDetailsPanel);
        BranchDetailsPanel.setBounds(200, 220, 740, 370);

        EnterBrannchID.setText("# Enter Branch ID");
        EnterBrannchID.addActionListener(this::EnterBrannchIDActionPerformed);
        MainPanel.add(EnterBrannchID);
        EnterBrannchID.setBounds(200, 90, 430, 50);

        jPanel2.setLayout(null);
        MainPanel.add(jPanel2);
        jPanel2.setBounds(180, 0, 870, 70);

        Create.setBackground(new java.awt.Color(168, 168, 168));
        Create.setText("Create+");
        Create.addActionListener(this::CreateActionPerformed);
        MainPanel.add(Create);
        Create.setBounds(669, 88, 96, 48);

        totalOrdersUP.setText("Total Orders");
        MainPanel.add(totalOrdersUP);
        totalOrdersUP.setBounds(250, 150, 100, 16);

        TotalEmployeesUP.setText("Total Employees");
        MainPanel.add(TotalEmployeesUP);
        TotalEmployeesUP.setBounds(360, 150, 100, 16);

        jPanel3.setLayout(null);

        totalEmployee.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalEmployee.setText("100");
        jPanel3.add(totalEmployee);
        totalEmployee.setBounds(0, 0, 90, 40);

        MainPanel.add(jPanel3);
        jPanel3.setBounds(360, 170, 90, 40);

        TotalOrders.setBackground(new java.awt.Color(255, 255, 255));
        TotalOrders.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TotalOrders.setText("100");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(TotalOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TotalOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MainPanel.add(jPanel4);
        jPanel4.setBounds(250, 170, 90, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EnterBrannchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterBrannchIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterBrannchIDActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveActionPerformed

    private void BranchIDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BranchIDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BranchIDTActionPerformed

    private void BranchNameTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BranchNameTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BranchNameTActionPerformed

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateActionPerformed

    private void BranchPhoneNumberTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BranchPhoneNumberTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BranchPhoneNumberTActionPerformed

    private void ManageOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageOrdersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManageOrdersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new branchlocationmgmt().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressReceiver;
    private javax.swing.JButton BranchAndNetworks;
    private javax.swing.JLabel BranchDetailsLabel;
    private javax.swing.JPanel BranchDetailsPanel;
    private javax.swing.JTextField BranchIDT;
    private javax.swing.JTextField BranchNameT;
    private javax.swing.JTextField BranchPhoneNumberT;
    private javax.swing.JButton Create;
    private javax.swing.JLabel DokoImage;
    private javax.swing.JButton Edit;
    private javax.swing.JTextField EmailT;
    private javax.swing.JTextField EnterBrannchID;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton ManageOrders;
    private javax.swing.JButton MyProfile;
    private javax.swing.JButton PriceConfiguration;
    private javax.swing.JLabel Profile;
    private javax.swing.JTextField ReceiverAddressT;
    private javax.swing.JButton Save;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JPanel Topbar;
    private javax.swing.JLabel TotalEmployeesUP;
    private javax.swing.JLabel TotalOrders;
    private javax.swing.JButton WorkLoad;
    private javax.swing.JLabel branchEmail;
    private javax.swing.JLabel branchID;
    private javax.swing.JLabel branchName;
    private javax.swing.JButton dashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton logout;
    private javax.swing.JButton manageUsers;
    private javax.swing.JLabel phoneNumberBranch;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel totalEmployee;
    private javax.swing.JLabel totalOrdersUP;
    // End of variables declaration//GEN-END:variables
}
