/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author unishgautam
 */
public class forgotPassword extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(forgotPassword.class.getName());

    /**
     * Creates new form forgotPassword
     */
    public forgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Fullname = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        otp = new javax.swing.JLabel();
        NewPassword = new javax.swing.JLabel();
        ConfirmNewpassword = new javax.swing.JLabel();
        FullnameTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        OtpTextField = new javax.swing.JTextField();
        ConfirmNewPasswordField = new javax.swing.JPasswordField();
        NewPasswordField = new javax.swing.JPasswordField();
        ForgetPassword = new javax.swing.JLabel();
        WhyYouForget = new javax.swing.JLabel();
        OtpButton = new javax.swing.JButton();
        ChangePassword = new javax.swing.JButton();
        TermsCheckBox = new javax.swing.JCheckBox();
        DOKO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(236, 236, 236));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(217, 217, 217), new java.awt.Color(217, 217, 217), new java.awt.Color(217, 217, 217), new java.awt.Color(217, 217, 217)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        Fullname.setText("Fullname");
        jPanel1.add(Fullname);
        Fullname.setBounds(30, 140, 49, 16);

        Email.setText("Email");
        jPanel1.add(Email);
        Email.setBounds(30, 180, 70, 16);

        otp.setText("OTP");
        jPanel1.add(otp);
        otp.setBounds(30, 220, 30, 16);

        NewPassword.setText("New password");
        jPanel1.add(NewPassword);
        NewPassword.setBounds(30, 270, 110, 16);

        ConfirmNewpassword.setText("Confirm new password");
        jPanel1.add(ConfirmNewpassword);
        ConfirmNewpassword.setBounds(30, 300, 122, 16);

        FullnameTextField.setBackground(new java.awt.Color(217, 217, 217));
        FullnameTextField.setText("Unish Gautam");
        FullnameTextField.addActionListener(this::FullnameTextFieldActionPerformed);
        jPanel1.add(FullnameTextField);
        FullnameTextField.setBounds(180, 130, 298, 22);

        EmailTextField.setBackground(new java.awt.Color(217, 217, 217));
        EmailTextField.setText("unishgautam07@gmail.com");
        jPanel1.add(EmailTextField);
        EmailTextField.setBounds(180, 180, 203, 22);

        OtpTextField.setBackground(new java.awt.Color(217, 217, 217));
        OtpTextField.setText("123456789");
        OtpTextField.addActionListener(this::OtpTextFieldActionPerformed);
        jPanel1.add(OtpTextField);
        OtpTextField.setBounds(180, 220, 298, 22);

        ConfirmNewPasswordField.setBackground(new java.awt.Color(217, 217, 217));
        ConfirmNewPasswordField.setText("jPasswordField1");
        ConfirmNewPasswordField.addActionListener(this::ConfirmNewPasswordFieldActionPerformed);
        jPanel1.add(ConfirmNewPasswordField);
        ConfirmNewPasswordField.setBounds(180, 300, 298, 22);

        NewPasswordField.setBackground(new java.awt.Color(217, 217, 217));
        NewPasswordField.setText("jPasswordField2");
        NewPasswordField.addActionListener(this::NewPasswordFieldActionPerformed);
        jPanel1.add(NewPasswordField);
        NewPasswordField.setBounds(180, 260, 298, 22);

        ForgetPassword.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        ForgetPassword.setForeground(new java.awt.Color(41, 51, 123));
        ForgetPassword.setText("Forget password ");
        jPanel1.add(ForgetPassword);
        ForgetPassword.setBounds(170, 30, 201, 32);

        WhyYouForget.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        WhyYouForget.setText("Why you forget?");
        jPanel1.add(WhyYouForget);
        WhyYouForget.setBounds(190, 70, 170, 24);

        OtpButton.setBackground(new java.awt.Color(217, 217, 217));
        OtpButton.setText("Send OTP");
        OtpButton.addActionListener(this::OtpButtonActionPerformed);
        jPanel1.add(OtpButton);
        OtpButton.setBounds(390, 180, 82, 22);

        ChangePassword.setBackground(new java.awt.Color(213, 173, 100));
        ChangePassword.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        ChangePassword.setForeground(new java.awt.Color(255, 255, 255));
        ChangePassword.setText("Change Password");
        ChangePassword.addActionListener(this::ChangePasswordActionPerformed);
        jPanel1.add(ChangePassword);
        ChangePassword.setBounds(170, 420, 165, 32);

        TermsCheckBox.setText("Terms & Condition");
        jPanel1.add(TermsCheckBox);
        TermsCheckBox.setBounds(170, 390, 125, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(292, 26, 520, 470);

        DOKO.setBackground(new java.awt.Color(41, 51, 123));
        DOKO.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        DOKO.setForeground(new java.awt.Color(41, 51, 123));
        DOKO.setText("DOKO");
        getContentPane().add(DOKO);
        DOKO.setBounds(6, 0, 150, 47);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FullnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FullnameTextFieldActionPerformed

    private void OtpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OtpTextFieldActionPerformed

    private void ConfirmNewPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmNewPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmNewPasswordFieldActionPerformed

    private void NewPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewPasswordFieldActionPerformed

    private void OtpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtpButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OtpButtonActionPerformed

    private void ChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangePasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new forgotPassword().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangePassword;
    private javax.swing.JPasswordField ConfirmNewPasswordField;
    private javax.swing.JLabel ConfirmNewpassword;
    private javax.swing.JLabel DOKO;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel ForgetPassword;
    private javax.swing.JLabel Fullname;
    private javax.swing.JTextField FullnameTextField;
    private javax.swing.JLabel NewPassword;
    private javax.swing.JPasswordField NewPasswordField;
    private javax.swing.JButton OtpButton;
    private javax.swing.JTextField OtpTextField;
    private javax.swing.JCheckBox TermsCheckBox;
    private javax.swing.JLabel WhyYouForget;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel otp;
    // End of variables declaration//GEN-END:variables
}
