/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Kushal
 */
public class login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());

    /**
     * Creates new form sign_up
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        track_parcel_label = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        username_txtfld = new javax.swing.JTextField();
        username_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        password_txtfld = new javax.swing.JTextField();
        loginbtn = new javax.swing.JButton();
        whatsup = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dont_have_act_label = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();
        forgotPassword = new javax.swing.JButton();
        tracking_id_label = new javax.swing.JLabel();
        tracking_id_textfield = new javax.swing.JTextField();
        orderSearch = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        total_cost_value = new javax.swing.JTextField();
        receiveraddresstextfield1 = new javax.swing.JTextField();
        senderaddresstextfield1 = new javax.swing.JTextField();
        receiveremailtextfield1 = new javax.swing.JTextField();
        receivernametextfield1 = new javax.swing.JTextField();
        trackingidtextfield1 = new javax.swing.JTextField();
        trackingIDlabel1 = new javax.swing.JLabel();
        receivernamelabel1 = new javax.swing.JLabel();
        receiveremaillabel1 = new javax.swing.JLabel();
        senderaddresslabel1 = new javax.swing.JLabel();
        receiveraddresslabel1 = new javax.swing.JLabel();
        totalcostlabel1 = new javax.swing.JLabel();
        Orderdetaillabel1 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(236, 236, 236));
        jPanel3.setLayout(null);

        track_parcel_label.setFont(new java.awt.Font("REM", 0, 48)); // NOI18N
        track_parcel_label.setForeground(new java.awt.Color(41, 51, 123));
        track_parcel_label.setText("Track Your Parcel ");
        jPanel3.add(track_parcel_label);
        track_parcel_label.setBounds(58, 0, 420, 62);

        jPanel2.setBackground(new java.awt.Color(236, 236, 236));
        jPanel2.setLayout(null);

        username_txtfld.addActionListener(this::username_txtfldActionPerformed);
        jPanel2.add(username_txtfld);
        username_txtfld.setBounds(120, 110, 145, 30);

        username_label.setFont(new java.awt.Font("REM", 0, 12)); // NOI18N
        username_label.setText("username");
        jPanel2.add(username_label);
        username_label.setBounds(40, 120, 63, 16);

        password_label.setFont(new java.awt.Font("REM", 0, 12)); // NOI18N
        password_label.setText("password");
        jPanel2.add(password_label);
        password_label.setBounds(40, 160, 63, 16);

        password_txtfld.addActionListener(this::password_txtfldActionPerformed);
        jPanel2.add(password_txtfld);
        password_txtfld.setBounds(120, 152, 145, 30);

        loginbtn.setBackground(new java.awt.Color(96, 188, 82));
        loginbtn.setFont(new java.awt.Font("Righteous", 0, 12)); // NOI18N
        loginbtn.setForeground(new java.awt.Color(255, 255, 255));
        loginbtn.setText("LOG IN");
        loginbtn.addActionListener(this::loginbtnActionPerformed);
        jPanel2.add(loginbtn);
        loginbtn.setBounds(120, 220, 145, 23);

        whatsup.setFont(new java.awt.Font("REM", 0, 18)); // NOI18N
        whatsup.setText("What's Up?");
        jPanel2.add(whatsup);
        whatsup.setBounds(120, 20, 110, 24);

        jLabel3.setFont(new java.awt.Font("Righteous", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(41, 51, 123));
        jLabel3.setText("Login");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(140, 40, 62, 47);

        dont_have_act_label.setFont(new java.awt.Font("Righteous", 0, 12)); // NOI18N
        dont_have_act_label.setText("Don't have an account ?");
        jPanel2.add(dont_have_act_label);
        dont_have_act_label.setBounds(60, 250, 140, 16);

        registerBtn.setText("Register");
        jPanel2.add(registerBtn);
        registerBtn.setBounds(190, 250, 100, 20);

        forgotPassword.setText("forget password?");
        jPanel2.add(forgotPassword);
        forgotPassword.setBounds(150, 190, 150, 20);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(550, 0, 332, 370);

        tracking_id_label.setFont(new java.awt.Font("REM", 0, 32)); // NOI18N
        tracking_id_label.setText("Enter tracking ID");
        jPanel3.add(tracking_id_label);
        tracking_id_label.setBounds(58, 66, 234, 42);

        tracking_id_textfield.setText("eg : 250455");
        tracking_id_textfield.addActionListener(this::tracking_id_textfieldActionPerformed);
        jPanel3.add(tracking_id_textfield);
        tracking_id_textfield.setBounds(58, 113, 258, 34);

        orderSearch.setText("Search");
        jPanel3.add(orderSearch);
        orderSearch.setBounds(320, 116, 80, 30);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168, 168, 168)));
        jPanel4.setLayout(null);

        total_cost_value.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        total_cost_value.setBorder(null);
        jPanel4.add(total_cost_value);
        total_cost_value.setBounds(169, 167, 280, 16);

        receiveraddresstextfield1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        receiveraddresstextfield1.setBorder(null);
        receiveraddresstextfield1.addActionListener(this::receiveraddresstextfield1ActionPerformed);
        jPanel4.add(receiveraddresstextfield1);
        receiveraddresstextfield1.setBounds(169, 133, 280, 16);

        senderaddresstextfield1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        senderaddresstextfield1.setBorder(null);
        jPanel4.add(senderaddresstextfield1);
        senderaddresstextfield1.setBounds(169, 111, 280, 16);

        receiveremailtextfield1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        receiveremailtextfield1.setBorder(null);
        receiveremailtextfield1.addActionListener(this::receiveremailtextfield1ActionPerformed);
        jPanel4.add(receiveremailtextfield1);
        receiveremailtextfield1.setBounds(169, 89, 280, 16);

        receivernametextfield1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        receivernametextfield1.setBorder(null);
        receivernametextfield1.addActionListener(this::receivernametextfield1ActionPerformed);
        jPanel4.add(receivernametextfield1);
        receivernametextfield1.setBounds(169, 67, 280, 16);

        trackingidtextfield1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        trackingidtextfield1.setBorder(null);
        trackingidtextfield1.addActionListener(this::trackingidtextfield1ActionPerformed);
        jPanel4.add(trackingidtextfield1);
        trackingidtextfield1.setBounds(169, 45, 280, 16);

        trackingIDlabel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        trackingIDlabel1.setText("Tracking ID:");
        jPanel4.add(trackingIDlabel1);
        trackingIDlabel1.setBounds(29, 45, 102, 16);

        receivernamelabel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        receivernamelabel1.setText("Receiver Name:");
        jPanel4.add(receivernamelabel1);
        receivernamelabel1.setBounds(29, 67, 79, 16);

        receiveremaillabel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        receiveremaillabel1.setText("Receiver Email:");
        jPanel4.add(receiveremaillabel1);
        receiveremaillabel1.setBounds(29, 89, 122, 16);

        senderaddresslabel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        senderaddresslabel1.setText("Sender Address:");
        jPanel4.add(senderaddresslabel1);
        senderaddresslabel1.setBounds(29, 111, 78, 16);

        receiveraddresslabel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        receiveraddresslabel1.setText("Receiver Address:");
        jPanel4.add(receiveraddresslabel1);
        receiveraddresslabel1.setBounds(29, 133, 87, 16);

        totalcostlabel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        totalcostlabel1.setText("Total cost:");
        jPanel4.add(totalcostlabel1);
        totalcostlabel1.setBounds(29, 167, 134, 16);

        Orderdetaillabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Orderdetaillabel1.setText("Order Details:");
        jPanel4.add(Orderdetaillabel1);
        Orderdetaillabel1.setBounds(32, 19, 117, 20);

        status.setText("status :");
        jPanel4.add(status);
        status.setBounds(310, 10, 150, 30);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(50, 160, 470, 190);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(80, 130, 880, 370);

        jLabel2.setFont(new java.awt.Font("Righteous", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(41, 51, 123));
        jLabel2.setText("DOKO");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 170, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void username_txtfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_txtfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_txtfldActionPerformed

    private void password_txtfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_txtfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_txtfldActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginbtnActionPerformed

    private void tracking_id_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tracking_id_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tracking_id_textfieldActionPerformed

    private void receiveraddresstextfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveraddresstextfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiveraddresstextfield1ActionPerformed

    private void receiveremailtextfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveremailtextfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiveremailtextfield1ActionPerformed

    private void receivernametextfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receivernametextfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receivernametextfield1ActionPerformed

    private void trackingidtextfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackingidtextfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trackingidtextfield1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Orderdetaillabel1;
    private javax.swing.JLabel dont_have_act_label;
    private javax.swing.JButton forgotPassword;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton loginbtn;
    private javax.swing.JButton orderSearch;
    private javax.swing.JLabel password_label;
    private javax.swing.JTextField password_txtfld;
    private javax.swing.JLabel receiveraddresslabel1;
    private javax.swing.JTextField receiveraddresstextfield1;
    private javax.swing.JLabel receiveremaillabel1;
    private javax.swing.JTextField receiveremailtextfield1;
    private javax.swing.JLabel receivernamelabel1;
    private javax.swing.JTextField receivernametextfield1;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLabel senderaddresslabel1;
    private javax.swing.JTextField senderaddresstextfield1;
    private javax.swing.JLabel status;
    private javax.swing.JTextField total_cost_value;
    private javax.swing.JLabel totalcostlabel1;
    private javax.swing.JLabel track_parcel_label;
    private javax.swing.JLabel trackingIDlabel1;
    private javax.swing.JLabel tracking_id_label;
    private javax.swing.JTextField tracking_id_textfield;
    private javax.swing.JTextField trackingidtextfield1;
    private javax.swing.JLabel username_label;
    private javax.swing.JTextField username_txtfld;
    private javax.swing.JLabel whatsup;
    // End of variables declaration//GEN-END:variables
    public String getUsername() {
        return username_txtfld.getText();
    }

    public String getPassword() {
        return password_txtfld.getText(); 
    }

    public void addLoginListener(java.awt.event.ActionListener listener) {
        loginbtn.addActionListener(listener);
    }
    public void addRegisterListener(java.awt.event.ActionListener listener) {
        // Make sure the variable name matches your NetBeans designer!
        registerBtn.addActionListener(listener); 
    }
    public void addForgotPassword(java.awt.event.ActionListener listener) {
        forgotPassword.addActionListener(listener); 
    }
    // =========================================================================
    // PUBLIC TRACKING LOGIC
    // =========================================================================

    public String getTrackingInput() {
        return tracking_id_textfield.getText().trim();
    }

    public void setTrackingResult(String tId, String name, String email, String sender, String receiver, String cost, String orderStatus) {
        trackingidtextfield1.setText(tId);
        receivernametextfield1.setText(name);
        receiveremailtextfield1.setText(email);
        senderaddresstextfield1.setText(sender);
        receiveraddresstextfield1.setText(receiver);
        total_cost_value.setText(cost);
        
        // Assuming 'status' is the JLabel for the actual value, not the title text
        status.setText(orderStatus); 
    }

    public void lockTrackingDisplayFields() {
        // Ensure users cannot type into the result boxes!
        trackingidtextfield1.setEditable(false);
        receivernametextfield1.setEditable(false);
        receiveremailtextfield1.setEditable(false);
        senderaddresstextfield1.setEditable(false);
        receiveraddresstextfield1.setEditable(false);
        total_cost_value.setEditable(false);
        
        // Clear them out by default
        setTrackingResult("", "", "", "", "", "", "---");
    }

    public void addOrderSearchListener(java.awt.event.ActionListener listener) {
        orderSearch.addActionListener(listener);
    }
  
        
}

