/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Kushal
 */
public class login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());

    /**
     * Creates new form sign_up
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        track_parcel_label = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        username_txtfld = new javax.swing.JTextField();
        username_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        password_txtfld = new javax.swing.JTextField();
        loginbtn = new javax.swing.JButton();
        change_pass_label = new javax.swing.JLabel();
        whatsup = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dont_have_act_label = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();
        tracking_id_label = new javax.swing.JLabel();
        tracking_id_textfield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        details_txt_area = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        orderSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(236, 236, 236));
        jPanel3.setLayout(null);

        track_parcel_label.setFont(new java.awt.Font("REM", 0, 48)); // NOI18N
        track_parcel_label.setForeground(new java.awt.Color(41, 51, 123));
        track_parcel_label.setText("Track Your Parcel ");
        jPanel3.add(track_parcel_label);
        track_parcel_label.setBounds(58, 0, 420, 62);

        jPanel2.setBackground(new java.awt.Color(236, 236, 236));
        jPanel2.setLayout(null);

        username_txtfld.addActionListener(this::username_txtfldActionPerformed);
        jPanel2.add(username_txtfld);
        username_txtfld.setBounds(120, 110, 145, 30);

        username_label.setFont(new java.awt.Font("REM", 0, 12)); // NOI18N
        username_label.setText("username");
        jPanel2.add(username_label);
        username_label.setBounds(40, 120, 63, 16);

        password_label.setFont(new java.awt.Font("REM", 0, 12)); // NOI18N
        password_label.setText("password");
        jPanel2.add(password_label);
        password_label.setBounds(40, 160, 63, 16);

        password_txtfld.addActionListener(this::password_txtfldActionPerformed);
        jPanel2.add(password_txtfld);
        password_txtfld.setBounds(120, 152, 145, 30);

        loginbtn.setBackground(new java.awt.Color(96, 188, 82));
        loginbtn.setFont(new java.awt.Font("Righteous", 0, 12)); // NOI18N
        loginbtn.setForeground(new java.awt.Color(255, 255, 255));
        loginbtn.setText("LOG IN");
        loginbtn.addActionListener(this::loginbtnActionPerformed);
        jPanel2.add(loginbtn);
        loginbtn.setBounds(120, 220, 145, 23);

        change_pass_label.setFont(new java.awt.Font("Righteous", 0, 10)); // NOI18N
        change_pass_label.setForeground(new java.awt.Color(41, 51, 123));
        change_pass_label.setText("forget password");
        jPanel2.add(change_pass_label);
        change_pass_label.setBounds(180, 190, 90, 14);

        whatsup.setFont(new java.awt.Font("REM", 0, 18)); // NOI18N
        whatsup.setText("What's Up?");
        jPanel2.add(whatsup);
        whatsup.setBounds(120, 20, 110, 24);

        jLabel3.setFont(new java.awt.Font("Righteous", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(41, 51, 123));
        jLabel3.setText("Login");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(140, 40, 62, 47);

        dont_have_act_label.setFont(new java.awt.Font("Righteous", 0, 12)); // NOI18N
        dont_have_act_label.setText("Don't have an account ?");
        jPanel2.add(dont_have_act_label);
        dont_have_act_label.setBounds(60, 250, 140, 16);

        registerBtn.setText("Register");
        jPanel2.add(registerBtn);
        registerBtn.setBounds(190, 250, 100, 20);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(550, 0, 332, 370);

        tracking_id_label.setFont(new java.awt.Font("REM", 0, 32)); // NOI18N
        tracking_id_label.setText("Enter tracking ID");
        jPanel3.add(tracking_id_label);
        tracking_id_label.setBounds(58, 66, 234, 42);

        tracking_id_textfield.setText("eg_250455");
        tracking_id_textfield.addActionListener(this::tracking_id_textfieldActionPerformed);
        jPanel3.add(tracking_id_textfield);
        tracking_id_textfield.setBounds(58, 113, 258, 34);

        details_txt_area.setColumns(20);
        details_txt_area.setRows(5);
        jScrollPane1.setViewportView(details_txt_area);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(60, 190, 419, 149);

        jLabel1.setFont(new java.awt.Font("REM", 0, 14)); // NOI18N
        jLabel1.setText("Details");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(60, 170, 50, 19);

        orderSearch.setText("Search");
        jPanel3.add(orderSearch);
        orderSearch.setBounds(320, 116, 80, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(80, 130, 880, 370);

        jLabel2.setFont(new java.awt.Font("Righteous", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(41, 51, 123));
        jLabel2.setText("DOKO");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 170, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void username_txtfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_txtfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_txtfldActionPerformed

    private void password_txtfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_txtfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_txtfldActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginbtnActionPerformed

    private void tracking_id_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tracking_id_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tracking_id_textfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel change_pass_label;
    private javax.swing.JTextArea details_txt_area;
    private javax.swing.JLabel dont_have_act_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loginbtn;
    private javax.swing.JButton orderSearch;
    private javax.swing.JLabel password_label;
    private javax.swing.JTextField password_txtfld;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLabel track_parcel_label;
    private javax.swing.JLabel tracking_id_label;
    private javax.swing.JTextField tracking_id_textfield;
    private javax.swing.JLabel username_label;
    private javax.swing.JTextField username_txtfld;
    private javax.swing.JLabel whatsup;
    // End of variables declaration//GEN-END:variables
    public String getUsername() {
        return username_txtfld.getText();
    }

    public String getPassword() {
        return password_txtfld.getText(); 
    }

    public void addLoginListener(java.awt.event.ActionListener listener) {
        loginbtn.addActionListener(listener);
    }
    public void addRegisterListener(java.awt.event.ActionListener listener) {
        // Make sure the variable name matches your NetBeans designer!
        registerBtn.addActionListener(listener); 
    }
}

