/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author nischal
 */
public class Manager_active_orders extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Manager_active_orders.class.getName());

    /**
     * Creates new form Manager_active_orders
     */
    public Manager_active_orders() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Topbar = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        user_role = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderTable = new javax.swing.JTable();
        filter = new javax.swing.JButton();
        sidebar = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Dashboard = new javax.swing.JButton();
        ManageUser = new javax.swing.JButton();
        WorkLoad = new javax.swing.JButton();
        ActiveOrders = new javax.swing.JButton();
        manage_order = new javax.swing.JButton();
        AssignOrder = new javax.swing.JButton();
        MyProfile = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(238, 233, 223));
        MainPanel.setPreferredSize(new java.awt.Dimension(1050, 600));
        MainPanel.setLayout(null);

        Topbar.setBackground(new java.awt.Color(255, 255, 255));
        Topbar.setLayout(null);

        username.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        username.setText("Name");
        Topbar.add(username);
        username.setBounds(770, 20, 100, 22);

        user_role.setText("Role");
        Topbar.add(user_role);
        user_role.setBounds(770, 40, 100, 16);

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pfp.jpg"))); // NOI18N
        Topbar.add(profile);
        profile.setBounds(700, 5, 60, 60);

        MainPanel.add(Topbar);
        Topbar.setBounds(180, 0, 870, 75);

        OrderTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        OrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tracking ID", "Customer", "Contact", "Shipment", "Status", "Delivery Cost", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(OrderTable);

        MainPanel.add(jScrollPane1);
        jScrollPane1.setBounds(230, 170, 760, 440);

        filter.setText("Filter");
        MainPanel.add(filter);
        filter.setBounds(920, 120, 75, 23);

        sidebar.setBackground(new java.awt.Color(33, 38, 49));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N

        Dashboard.setBackground(new java.awt.Color(33, 38, 49));
        Dashboard.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard.setText("Dashboard");

        ManageUser.setBackground(new java.awt.Color(33, 38, 49));
        ManageUser.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        ManageUser.setForeground(new java.awt.Color(255, 255, 255));
        ManageUser.setText("Manage User");

        WorkLoad.setBackground(new java.awt.Color(33, 38, 49));
        WorkLoad.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        WorkLoad.setForeground(new java.awt.Color(255, 255, 255));
        WorkLoad.setText("Workload");

        ActiveOrders.setBackground(new java.awt.Color(216, 140, 81));
        ActiveOrders.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        ActiveOrders.setForeground(new java.awt.Color(255, 255, 255));
        ActiveOrders.setText("Active Orders");

        manage_order.setBackground(new java.awt.Color(33, 38, 49));
        manage_order.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        manage_order.setForeground(new java.awt.Color(255, 255, 255));
        manage_order.setText("Manage Order");

        AssignOrder.setBackground(new java.awt.Color(33, 38, 49));
        AssignOrder.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        AssignOrder.setForeground(new java.awt.Color(255, 255, 255));
        AssignOrder.setText("Assign Orders");

        MyProfile.setBackground(new java.awt.Color(33, 38, 49));
        MyProfile.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        MyProfile.setForeground(new java.awt.Color(255, 255, 255));
        MyProfile.setText("My Profile");

        logout.setBackground(new java.awt.Color(33, 38, 49));
        logout.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 51, 51));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(this::logoutActionPerformed);

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(ManageUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WorkLoad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ActiveOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manage_order, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AssignOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MyProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WorkLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ActiveOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manage_order, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AssignOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        MainPanel.add(sidebar);
        sidebar.setBounds(0, 0, 180, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Manager_active_orders().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActiveOrders;
    private javax.swing.JButton AssignOrder;
    private javax.swing.JButton Dashboard;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton ManageUser;
    private javax.swing.JButton MyProfile;
    private javax.swing.JTable OrderTable;
    private javax.swing.JPanel Topbar;
    private javax.swing.JButton WorkLoad;
    private javax.swing.JButton filter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo;
    private javax.swing.JButton logout;
    private javax.swing.JButton manage_order;
    private javax.swing.JLabel profile;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel user_role;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables

public void setUsernameLabel(String name) {
        username.setText(name); 
    }

    public void setRoleLabel(String role) {
        user_role.setText(role); 
    }

    public void addDashboardListener(java.awt.event.ActionListener listener) {
        Dashboard.addActionListener(listener); 
    }

    public void addLogoutListener(java.awt.event.ActionListener listener) {
        logout.addActionListener(listener); 
    }
public void addManageUserListener(java.awt.event.ActionListener listener) {
      ManageUser.addActionListener(listener);
}
public void addWorkloadListener(java.awt.event.ActionListener listener) {
       
        WorkLoad.addActionListener(listener); 
    }
public void addManageOrdersListener(java.awt.event.ActionListener listener) {
    manage_order.addActionListener(listener); 
}

public void addAssiggnedOrdersListener(java.awt.event.ActionListener listener) {
    AssignOrder.addActionListener(listener); 
}
public void addMyProfileListener(java.awt.event.ActionListener listener) {
       
        MyProfile.addActionListener(listener); 
    }

// =========================================================================
    // TABLE SETUP (DIRECT INJECTION)
    // =========================================================================

    public void clearTable() {
        ((javax.swing.table.DefaultTableModel)OrderTable.getModel()).setRowCount(0);
    }

    public void addTableRow(Object[] rowData) {
        ((javax.swing.table.DefaultTableModel)OrderTable.getModel()).addRow(rowData);
    }

    // =========================================================================
    // BUTTON LISTENERS
    // =========================================================================
    
    public void addFilterListener(java.awt.event.ActionListener listener) {
        // NOTE: Replace 'jButton1' or 'FilterBtn' with whatever you actually named 
        // the Filter button in your NetBeans Design tab!
        filter.addActionListener(listener); 
    }

}
