/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author User
 */
public class ManageUser extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageUser.class.getName());

    /**
     * Creates new form AdminOrderEdit
     */
    public ManageUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutbutton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        ManageUserButton = new javax.swing.JButton();
        workLoadButton = new javax.swing.JButton();
        MyProfileButton = new javax.swing.JButton();
        Dashboardbutton = new javax.swing.JButton();
        branchAndNetworksButton = new javax.swing.JButton();
        ManageOrderButton = new javax.swing.JButton();
        PriceConfigurationButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        employeeIdTextF = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        Topbar = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        role = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        edit_of_email_and_number_panel = new javax.swing.JPanel();
        employee_ID = new javax.swing.JLabel();
        employee_details = new javax.swing.JLabel();
        Employee_Name = new javax.swing.JLabel();
        Employee_Email = new javax.swing.JLabel();
        Employee_Phone = new javax.swing.JLabel();
        Employee_Email_value = new javax.swing.JLabel();
        Employee_ID_value = new javax.swing.JLabel();
        Employee_Name_value = new javax.swing.JLabel();
        Employee_Phone_value = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1050, 600));
        getContentPane().setLayout(null);

        logoutbutton.setBackground(new java.awt.Color(33, 38, 49));
        logoutbutton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        logoutbutton.setForeground(new java.awt.Color(239, 68, 68));
        logoutbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        logoutbutton.setText("Logout");
        logoutbutton.setPreferredSize(new java.awt.Dimension(148, 50));
        getContentPane().add(logoutbutton);
        logoutbutton.setBounds(14, 544, 160, 50);

        jPanel3.setBackground(new java.awt.Color(33, 38, 49));
        jPanel3.setLayout(null);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(0, 531, 190, 10);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(0, 76, 190, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(99, 47));
        jPanel3.add(jLabel1);
        jLabel1.setBounds(6, 6, 169, 64);

        ManageUserButton.setBackground(new java.awt.Color(216, 140, 81));
        ManageUserButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        ManageUserButton.setForeground(new java.awt.Color(255, 255, 255));
        ManageUserButton.setText("Manage User");
        jPanel3.add(ManageUserButton);
        ManageUserButton.setBounds(10, 150, 170, 50);

        workLoadButton.setBackground(new java.awt.Color(33, 38, 49));
        workLoadButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        workLoadButton.setForeground(new java.awt.Color(255, 255, 255));
        workLoadButton.setText("Workload");
        jPanel3.add(workLoadButton);
        workLoadButton.setBounds(10, 210, 170, 50);

        MyProfileButton.setBackground(new java.awt.Color(33, 38, 49));
        MyProfileButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        MyProfileButton.setForeground(new java.awt.Color(255, 255, 255));
        MyProfileButton.setText("My Profile");
        MyProfileButton.addActionListener(this::MyProfileButtonActionPerformed);
        jPanel3.add(MyProfileButton);
        MyProfileButton.setBounds(10, 450, 170, 50);

        Dashboardbutton.setBackground(new java.awt.Color(33, 38, 49));
        Dashboardbutton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        Dashboardbutton.setForeground(new java.awt.Color(255, 255, 255));
        Dashboardbutton.setText("Dashboard");
        jPanel3.add(Dashboardbutton);
        Dashboardbutton.setBounds(10, 90, 170, 50);

        branchAndNetworksButton.setBackground(new java.awt.Color(33, 38, 49));
        branchAndNetworksButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        branchAndNetworksButton.setForeground(new java.awt.Color(255, 255, 255));
        branchAndNetworksButton.setText("Branch and Network");
        branchAndNetworksButton.setPreferredSize(new java.awt.Dimension(99, 27));
        branchAndNetworksButton.addActionListener(this::branchAndNetworksButtonActionPerformed);
        jPanel3.add(branchAndNetworksButton);
        branchAndNetworksButton.setBounds(10, 270, 170, 50);

        ManageOrderButton.setBackground(new java.awt.Color(33, 38, 49));
        ManageOrderButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        ManageOrderButton.setForeground(new java.awt.Color(255, 255, 255));
        ManageOrderButton.setText("Manage Order");
        jPanel3.add(ManageOrderButton);
        ManageOrderButton.setBounds(10, 330, 170, 50);

        PriceConfigurationButton.setBackground(new java.awt.Color(33, 38, 49));
        PriceConfigurationButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        PriceConfigurationButton.setForeground(new java.awt.Color(255, 255, 255));
        PriceConfigurationButton.setText("Price Configuration");
        jPanel3.add(PriceConfigurationButton);
        PriceConfigurationButton.setBounds(10, 390, 170, 50);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 190, 600);

        jPanel2.setBackground(new java.awt.Color(238, 233, 223));
        jPanel2.setLayout(null);

        employeeIdTextF.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        employeeIdTextF.setText("#Enter Employee ID");
        employeeIdTextF.setPreferredSize(new java.awt.Dimension(626, 65));
        employeeIdTextF.addActionListener(this::employeeIdTextFActionPerformed);
        jPanel2.add(employeeIdTextF);
        employeeIdTextF.setBounds(260, 150, 420, 46);

        searchButton.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        searchButton.setText("Search");
        jPanel2.add(searchButton);
        searchButton.setBounds(700, 150, 94, 46);

        Topbar.setLayout(null);

        name.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        name.setText("Name");
        Topbar.add(name);
        name.setBounds(770, 20, 100, 22);

        role.setText("Role");
        Topbar.add(role);
        role.setBounds(770, 40, 90, 16);

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pfp.jpg"))); // NOI18N
        Topbar.add(profile);
        profile.setBounds(700, 6, 60, 60);

        jPanel2.add(Topbar);
        Topbar.setBounds(180, 0, 870, 70);

        edit_of_email_and_number_panel.setBackground(new java.awt.Color(255, 255, 255));
        edit_of_email_and_number_panel.setPreferredSize(new java.awt.Dimension(200, 200));
        edit_of_email_and_number_panel.setLayout(null);

        employee_ID.setText("Employee ID");
        edit_of_email_and_number_panel.add(employee_ID);
        employee_ID.setBounds(26, 93, 100, 32);

        employee_details.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        employee_details.setText("Employee Details");
        edit_of_email_and_number_panel.add(employee_details);
        employee_details.setBounds(30, 29, 160, 32);

        Employee_Name.setText("Employee Name");
        edit_of_email_and_number_panel.add(Employee_Name);
        Employee_Name.setBounds(26, 131, 100, 35);

        Employee_Email.setText("Employee Email");
        edit_of_email_and_number_panel.add(Employee_Email);
        Employee_Email.setBounds(26, 172, 100, 35);

        Employee_Phone.setText("Phone Number");
        edit_of_email_and_number_panel.add(Employee_Phone);
        Employee_Phone.setBounds(26, 213, 90, 35);

        Employee_Email_value.setText(": ram@gmail.com");
        edit_of_email_and_number_panel.add(Employee_Email_value);
        Employee_Email_value.setBounds(139, 173, 270, 32);

        Employee_ID_value.setText(": #11111");
        edit_of_email_and_number_panel.add(Employee_ID_value);
        Employee_ID_value.setBounds(139, 93, 210, 32);

        Employee_Name_value.setText(": Ram");
        edit_of_email_and_number_panel.add(Employee_Name_value);
        Employee_Name_value.setBounds(139, 134, 230, 32);

        Employee_Phone_value.setText(": 980000000000");
        edit_of_email_and_number_panel.add(Employee_Phone_value);
        Employee_Phone_value.setBounds(139, 213, 280, 32);

        editBtn.setBackground(new java.awt.Color(242, 242, 242));
        editBtn.setText("Edit");
        edit_of_email_and_number_panel.add(editBtn);
        editBtn.setBounds(599, 30, 72, 31);

        savebtn.setBackground(new java.awt.Color(242, 242, 242));
        savebtn.setText("Save");
        savebtn.addActionListener(this::savebtnActionPerformed);
        edit_of_email_and_number_panel.add(savebtn);
        savebtn.setBounds(599, 266, 72, 31);

        jPanel2.add(edit_of_email_and_number_panel);
        edit_of_email_and_number_panel.setBounds(250, 240, 700, 330);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1050, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void branchAndNetworksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchAndNetworksButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branchAndNetworksButtonActionPerformed

    private void employeeIdTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeIdTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeIdTextFActionPerformed

    private void MyProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyProfileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MyProfileButtonActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dashboardbutton;
    private javax.swing.JLabel Employee_Email;
    private javax.swing.JLabel Employee_Email_value;
    private javax.swing.JLabel Employee_ID_value;
    private javax.swing.JLabel Employee_Name;
    private javax.swing.JLabel Employee_Name_value;
    private javax.swing.JLabel Employee_Phone;
    private javax.swing.JLabel Employee_Phone_value;
    private javax.swing.JButton ManageOrderButton;
    private javax.swing.JButton ManageUserButton;
    private javax.swing.JButton MyProfileButton;
    private javax.swing.JButton PriceConfigurationButton;
    private javax.swing.JPanel Topbar;
    private javax.swing.JButton branchAndNetworksButton;
    private javax.swing.JButton editBtn;
    private javax.swing.JPanel edit_of_email_and_number_panel;
    private javax.swing.JTextField employeeIdTextF;
    private javax.swing.JLabel employee_ID;
    private javax.swing.JLabel employee_details;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JLabel name;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel role;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton workLoadButton;
    // End of variables declaration//GEN-END:variables
// =========================================================================
    // GETTERS & SETTERS
    // =========================================================================
    public String getSearchIdInput() { 
        return employeeIdTextF.getText().trim(); 
    }
    
    // Setters for the display labels
    public void setEmployeeIdLabel(String text) { Employee_ID_value.setText(text); }
    public void setEmployeeNameLabel(String text) { Employee_Name_value.setText(text); }
    public void setEmployeeEmailLabel(String text) { Employee_Email_value.setText(text); }
    public void setEmployeePhoneLabel(String text) { Employee_Phone_value.setText(text); }
    
    // Getters to read the current label values before saving
    public String getCurrentDisplayedEmail() { return Employee_Email_value.getText(); }
    public String getCurrentDisplayedPhone() { return Employee_Phone_value.getText(); }

    // Top right profile labels
    public void setUsernameLabel(String text) { name.setText(text); }
    public void setRoleLabel(String text) { role.setText(text); }

    // =========================================================================
    // ACTION LISTENERS
    // =========================================================================
    public void addSearchListener(java.awt.event.ActionListener listener) { searchButton.addActionListener(listener); }
    public void addEditListener(java.awt.event.ActionListener listener) { editBtn.addActionListener(listener); }
    public void addSaveListener(java.awt.event.ActionListener listener) { savebtn.addActionListener(listener); }
    
    public void addDashboardListener(java.awt.event.ActionListener listener) { Dashboardbutton.addActionListener(listener); }
    public void addLogoutListener(java.awt.event.ActionListener listener) { logoutbutton.addActionListener(listener); }
    public void addWorkloadListener(java.awt.event.ActionListener listener) { workLoadButton.addActionListener(listener); }
    public void addManageOrdersListener(java.awt.event.ActionListener listener) { ManageOrderButton.addActionListener(listener); }
     public void addbranchNetwork(java.awt.event.ActionListener listener) { branchAndNetworksButton.addActionListener(listener); }
     public void addPriceConfiguration(java.awt.event.ActionListener listener) {PriceConfigurationButton .addActionListener(listener); }
      public void addMyProfileListener(java.awt.event.ActionListener listener) { 
        MyProfileButton.addActionListener(listener); 
    }
   
}

