/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author User
 */
public class ManageUser extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageUser.class.getName());

    /**
     * Creates new form AdminOrderEdit
     */
    public ManageUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutbutton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        ManageUserButton = new javax.swing.JButton();
        workLoadButton = new javax.swing.JButton();
        MyProfileButton = new javax.swing.JButton();
        Dashboardbutton = new javax.swing.JButton();
        branchAndNetworksButton = new javax.swing.JButton();
        ManageOrderButton = new javax.swing.JButton();
        PriceConfigurationButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        employeeIdTextF = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        Topbar = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        role = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        phoneNumbertextfield = new javax.swing.JTextField();
        employeeEmailTextField = new javax.swing.JTextField();
        employeeNameTextfield1 = new javax.swing.JTextField();
        employeeIDtextfield = new javax.swing.JTextField();
        employeeIDLabel = new javax.swing.JLabel();
        employeeNameLabel = new javax.swing.JLabel();
        employeeEmailLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        employeeDetailsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        logoutbutton.setBackground(new java.awt.Color(33, 38, 49));
        logoutbutton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        logoutbutton.setForeground(new java.awt.Color(239, 68, 68));
        logoutbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        logoutbutton.setText("Logout");
        logoutbutton.setPreferredSize(new java.awt.Dimension(148, 50));
        getContentPane().add(logoutbutton);
        logoutbutton.setBounds(14, 544, 160, 50);

        jPanel3.setBackground(new java.awt.Color(33, 38, 49));
        jPanel3.setLayout(null);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(0, 531, 190, 10);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(0, 76, 190, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(99, 47));
        jPanel3.add(jLabel1);
        jLabel1.setBounds(6, 6, 169, 64);

        ManageUserButton.setBackground(new java.awt.Color(216, 140, 81));
        ManageUserButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        ManageUserButton.setForeground(new java.awt.Color(255, 255, 255));
        ManageUserButton.setText("Manage User");
        jPanel3.add(ManageUserButton);
        ManageUserButton.setBounds(10, 150, 170, 50);

        workLoadButton.setBackground(new java.awt.Color(33, 38, 49));
        workLoadButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        workLoadButton.setForeground(new java.awt.Color(255, 255, 255));
        workLoadButton.setText("Workload");
        jPanel3.add(workLoadButton);
        workLoadButton.setBounds(10, 210, 170, 50);

        MyProfileButton.setBackground(new java.awt.Color(33, 38, 49));
        MyProfileButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        MyProfileButton.setForeground(new java.awt.Color(255, 255, 255));
        MyProfileButton.setText("My Profile");
        MyProfileButton.addActionListener(this::MyProfileButtonActionPerformed);
        jPanel3.add(MyProfileButton);
        MyProfileButton.setBounds(10, 450, 170, 50);

        Dashboardbutton.setBackground(new java.awt.Color(33, 38, 49));
        Dashboardbutton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        Dashboardbutton.setForeground(new java.awt.Color(255, 255, 255));
        Dashboardbutton.setText("Dashboard");
        jPanel3.add(Dashboardbutton);
        Dashboardbutton.setBounds(10, 90, 170, 50);

        branchAndNetworksButton.setBackground(new java.awt.Color(33, 38, 49));
        branchAndNetworksButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        branchAndNetworksButton.setForeground(new java.awt.Color(255, 255, 255));
        branchAndNetworksButton.setText("Branch and Network");
        branchAndNetworksButton.setPreferredSize(new java.awt.Dimension(99, 27));
        branchAndNetworksButton.addActionListener(this::branchAndNetworksButtonActionPerformed);
        jPanel3.add(branchAndNetworksButton);
        branchAndNetworksButton.setBounds(10, 270, 170, 50);

        ManageOrderButton.setBackground(new java.awt.Color(33, 38, 49));
        ManageOrderButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        ManageOrderButton.setForeground(new java.awt.Color(255, 255, 255));
        ManageOrderButton.setText("Manage Order");
        jPanel3.add(ManageOrderButton);
        ManageOrderButton.setBounds(10, 330, 170, 50);

        PriceConfigurationButton.setBackground(new java.awt.Color(33, 38, 49));
        PriceConfigurationButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        PriceConfigurationButton.setForeground(new java.awt.Color(255, 255, 255));
        PriceConfigurationButton.setText("Price Configuration");
        jPanel3.add(PriceConfigurationButton);
        PriceConfigurationButton.setBounds(10, 390, 170, 50);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 190, 600);

        jPanel2.setBackground(new java.awt.Color(238, 233, 223));
        jPanel2.setLayout(null);

        employeeIdTextF.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        employeeIdTextF.setText("#Enter Employee ID");
        employeeIdTextF.setPreferredSize(new java.awt.Dimension(626, 65));
        employeeIdTextF.addActionListener(this::employeeIdTextFActionPerformed);
        jPanel2.add(employeeIdTextF);
        employeeIdTextF.setBounds(260, 150, 420, 46);

        searchButton.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        searchButton.setText("Search");
        jPanel2.add(searchButton);
        searchButton.setBounds(700, 150, 94, 46);

        Topbar.setLayout(null);

        name.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        name.setText("Name");
        Topbar.add(name);
        name.setBounds(770, 20, 100, 22);

        role.setText("Role");
        Topbar.add(role);
        role.setBounds(770, 40, 90, 16);

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pfp.jpg"))); // NOI18N
        Topbar.add(profile);
        profile.setBounds(700, 6, 60, 60);

        jPanel2.add(Topbar);
        Topbar.setBounds(180, 0, 870, 70);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168, 168, 168)));
        jPanel4.setLayout(null);

        saveButton.setBackground(new java.awt.Color(244, 246, 248));
        saveButton.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        saveButton.setText("Save");
        jPanel4.add(saveButton);
        saveButton.setBounds(640, 190, 72, 32);

        editButton.setBackground(new java.awt.Color(244, 246, 248));
        editButton.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        editButton.setText("Edit");
        jPanel4.add(editButton);
        editButton.setBounds(634, 19, 72, 32);

        phoneNumbertextfield.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        phoneNumbertextfield.setText("eg : 9876543210");
        phoneNumbertextfield.setBorder(null);
        jPanel4.add(phoneNumbertextfield);
        phoneNumbertextfield.setBounds(210, 180, 280, 30);

        employeeEmailTextField.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        employeeEmailTextField.setText("eg : ram@gmail.com ");
        employeeEmailTextField.setBorder(null);
        employeeEmailTextField.addActionListener(this::employeeEmailTextFieldActionPerformed);
        jPanel4.add(employeeEmailTextField);
        employeeEmailTextField.setBounds(210, 140, 280, 25);

        employeeNameTextfield1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        employeeNameTextfield1.setText("eg :Ram");
        employeeNameTextfield1.setBorder(null);
        employeeNameTextfield1.addActionListener(this::employeeNameTextfield1ActionPerformed);
        jPanel4.add(employeeNameTextfield1);
        employeeNameTextfield1.setBounds(210, 100, 280, 25);

        employeeIDtextfield.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        employeeIDtextfield.setText("eg: #114351");
        employeeIDtextfield.setBorder(null);
        employeeIDtextfield.addActionListener(this::employeeIDtextfieldActionPerformed);
        jPanel4.add(employeeIDtextfield);
        employeeIDtextfield.setBounds(210, 60, 280, 25);

        employeeIDLabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        employeeIDLabel.setText("Employee ID:");
        jPanel4.add(employeeIDLabel);
        employeeIDLabel.setBounds(29, 61, 160, 25);

        employeeNameLabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        employeeNameLabel.setText("Employee Name");
        jPanel4.add(employeeNameLabel);
        employeeNameLabel.setBounds(29, 98, 170, 25);

        employeeEmailLabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        employeeEmailLabel.setText("Employee Email:");
        jPanel4.add(employeeEmailLabel);
        employeeEmailLabel.setBounds(29, 141, 160, 25);

        phoneNumberLabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        phoneNumberLabel.setText("Phone Number");
        jPanel4.add(phoneNumberLabel);
        phoneNumberLabel.setBounds(29, 186, 160, 25);

        employeeDetailsLabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        employeeDetailsLabel.setText("Employee Details:");
        jPanel4.add(employeeDetailsLabel);
        employeeDetailsLabel.setBounds(32, 19, 180, 25);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(250, 230, 750, 260);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1050, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void branchAndNetworksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchAndNetworksButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branchAndNetworksButtonActionPerformed

    private void employeeIdTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeIdTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeIdTextFActionPerformed

    private void employeeEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeEmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeEmailTextFieldActionPerformed

    private void employeeNameTextfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeNameTextfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeNameTextfield1ActionPerformed

    private void MyProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyProfileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MyProfileButtonActionPerformed

    private void employeeIDtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeIDtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeIDtextfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dashboardbutton;
    private javax.swing.JButton ManageOrderButton;
    private javax.swing.JButton ManageUserButton;
    private javax.swing.JButton MyProfileButton;
    private javax.swing.JButton PriceConfigurationButton;
    private javax.swing.JPanel Topbar;
    private javax.swing.JButton branchAndNetworksButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel employeeDetailsLabel;
    private javax.swing.JLabel employeeEmailLabel;
    private javax.swing.JTextField employeeEmailTextField;
    private javax.swing.JLabel employeeIDLabel;
    private javax.swing.JTextField employeeIDtextfield;
    private javax.swing.JTextField employeeIdTextF;
    private javax.swing.JLabel employeeNameLabel;
    private javax.swing.JTextField employeeNameTextfield1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumbertextfield;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel role;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton workLoadButton;
    // End of variables declaration//GEN-END:variables
// =========================================================================
    // TOP BAR & SEARCH INPUT
    // =========================================================================

//    public void setTopBar(String userName, String userRole) {
//        name.setText(userName);
//        role.setText(userRole);
//    }
//
//    public String getSearchInput() {
//        return employeeIdTextF.getText().trim();
//    }
//
//    // =========================================================================
//    // DATA INJECTION & LOCKING
//    // =========================================================================
//
//    public void setOrderDetails(String trackingId, String receiverName, String email, String senderAddr, String receiverAddr, String cost) {
//        employeeIDtextfield.setText(trackingId); 
//        employeeNameTextfield1.setText(receiverName);
//        employeeEmailTextField.setText(email);
//        phoneNumbertextfield.setText(senderAddr);
//        receiveraddresstextfield1.setText(receiverAddr);
//        total_cost_value.setText(cost); 
//    }
//
//    public void setFormEditable(boolean isEditable) {
//        // Locked fields that the employee can NEVER change here
//        employeeIDtextfield.setEditable(false); 
//        phoneNumbertextfield.setEditable(false);
//        
//        // Allowed fields
//        employeeNameTextfield1.setEditable(isEditable);
//        employeeEmailTextField.setEditable(isEditable);
//        receiveraddresstextfield1.setEditable(isEditable);
//        total_cost_value.setEditable(isEditable);
//        
//        // Toggle buttons
//        saveButton.setEnabled(isEditable);
//        editButton.setEnabled(!isEditable);
//    }
//
//    // Grab updated data for the database
//    public String getUpdatedName() { return employeeNameTextfield1.getText().trim(); }
//    public String getUpdatedEmail() { return employeeEmailTextField.getText().trim(); }
//    public String getUpdatedAddress() { return receiveraddresstextfield1.getText().trim(); }
//    public String getUpdatedCost() { return total_cost_value.getText().trim(); }
//
//    // =========================================================================
//    // BUTTON LISTENERS
//    // =========================================================================
//    
//    public void addSearchListener(java.awt.event.ActionListener listener) { searchButton.addActionListener(listener); }
//    public void addEditListener(java.awt.event.ActionListener listener) { editButton.addActionListener(listener); }
//    public void addSaveListener(java.awt.event.ActionListener listener) { saveButton.addActionListener(listener); }
//    
//    // Navigators
//    public void addDashboardListener(java.awt.event.ActionListener listener) { Dashboardbutton.addActionListener(listener); }
//    public void addLogoutListener(java.awt.event.ActionListener listener) { logoutbutton.addActionListener(listener); }

}
