/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author User
 */
public class ManagerOrderEdit extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManagerOrderEdit.class.getName());

    /**
     * Creates new form AdminOrderEdit
     */
    public ManagerOrderEdit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        TrackingIdtextfield = new javax.swing.JTextField();
        toppanel = new javax.swing.JPanel();
        namelabel = new javax.swing.JLabel();
        Rolelabel = new javax.swing.JLabel();
        pfplabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        savebutton = new javax.swing.JButton();
        editbutton = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        totalcostlabel = new javax.swing.JLabel();
        receiveraddresstextfield = new javax.swing.JTextField();
        senderaddresstextfield = new javax.swing.JTextField();
        receiveremailtextfield = new javax.swing.JTextField();
        receivernametextfield = new javax.swing.JTextField();
        trackingidtextfield = new javax.swing.JTextField();
        trackingIDlabel = new javax.swing.JLabel();
        receivernamelabel = new javax.swing.JLabel();
        receiveremaillabel = new javax.swing.JLabel();
        senderaddresslabel = new javax.swing.JLabel();
        receiveraddresslabel = new javax.swing.JLabel();
        Orderdetaillabel = new javax.swing.JLabel();
        returnbutton = new javax.swing.JButton();
        receivercontactlabel = new javax.swing.JLabel();
        receivercontacttextfield = new javax.swing.JTextField();
        searchbutton = new javax.swing.JButton();
        sidebar = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Dashboard = new javax.swing.JButton();
        ManageUser = new javax.swing.JButton();
        WorkLoad = new javax.swing.JButton();
        ActiveOrders = new javax.swing.JButton();
        ManageOrders = new javax.swing.JButton();
        AssignOrder = new javax.swing.JButton();
        MyProfile = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1050, 600));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(238, 233, 223));
        jPanel2.setLayout(null);

        TrackingIdtextfield.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        TrackingIdtextfield.setText("#Enter Tracking ID");
        TrackingIdtextfield.setPreferredSize(new java.awt.Dimension(626, 65));
        TrackingIdtextfield.addActionListener(this::TrackingIdtextfieldActionPerformed);
        jPanel2.add(TrackingIdtextfield);
        TrackingIdtextfield.setBounds(246, 104, 420, 46);

        toppanel.setBackground(new java.awt.Color(255, 255, 255));

        namelabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        namelabel.setText("Name");

        Rolelabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Rolelabel.setText("Role");

        pfplabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pfp.jpg"))); // NOI18N
        pfplabel.setText("jLabel2");

        javax.swing.GroupLayout toppanelLayout = new javax.swing.GroupLayout(toppanel);
        toppanel.setLayout(toppanelLayout);
        toppanelLayout.setHorizontalGroup(
            toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toppanelLayout.createSequentialGroup()
                .addContainerGap(714, Short.MAX_VALUE)
                .addComponent(pfplabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rolelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        toppanelLayout.setVerticalGroup(
            toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toppanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pfplabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(toppanelLayout.createSequentialGroup()
                        .addComponent(namelabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rolelabel)))
                .addGap(12, 12, 12))
        );

        jPanel2.add(toppanel);
        toppanel.setBounds(180, 0, 870, 74);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168, 168, 168)));
        jPanel1.setLayout(null);

        savebutton.setBackground(new java.awt.Color(244, 246, 248));
        savebutton.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        savebutton.setText("Save");
        jPanel1.add(savebutton);
        savebutton.setBounds(650, 330, 72, 32);

        editbutton.setBackground(new java.awt.Color(244, 246, 248));
        editbutton.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        editbutton.setText("Edit");
        jPanel1.add(editbutton);
        editbutton.setBounds(644, 19, 72, 32);

        jTextField7.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jTextField7.setText("1200");
        jTextField7.setBorder(null);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(160, 310, 280, 25);

        totalcostlabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        totalcostlabel.setText("Total cost:");
        jPanel1.add(totalcostlabel);
        totalcostlabel.setBounds(20, 310, 134, 25);

        receiveraddresstextfield.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        receiveraddresstextfield.setText("Kapan");
        receiveraddresstextfield.setBorder(null);
        jPanel1.add(receiveraddresstextfield);
        receiveraddresstextfield.setBounds(170, 270, 280, 25);

        senderaddresstextfield.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        senderaddresstextfield.setText("Dillibazar pipalbot");
        senderaddresstextfield.setBorder(null);
        jPanel1.add(senderaddresstextfield);
        senderaddresstextfield.setBounds(170, 230, 280, 30);

        receiveremailtextfield.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        receiveremailtextfield.setText("ram@gmail.com\n");
        receiveremailtextfield.setBorder(null);
        receiveremailtextfield.addActionListener(this::receiveremailtextfieldActionPerformed);
        jPanel1.add(receiveremailtextfield);
        receiveremailtextfield.setBounds(175, 155, 280, 25);

        receivernametextfield.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        receivernametextfield.setText("Ram");
        receivernametextfield.setBorder(null);
        jPanel1.add(receivernametextfield);
        receivernametextfield.setBounds(175, 112, 280, 25);

        trackingidtextfield.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        trackingidtextfield.setText("#1111");
        trackingidtextfield.setBorder(null);
        jPanel1.add(trackingidtextfield);
        trackingidtextfield.setBounds(175, 57, 280, 25);

        trackingIDlabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        trackingIDlabel.setText("Tracking ID:");
        jPanel1.add(trackingIDlabel);
        trackingIDlabel.setBounds(25, 57, 102, 25);

        receivernamelabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        receivernamelabel.setText("Receiver Name:");
        jPanel1.add(receivernamelabel);
        receivernamelabel.setBounds(25, 112, 122, 25);

        receiveremaillabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        receiveremaillabel.setText("Receiver Email:");
        jPanel1.add(receiveremaillabel);
        receiveremaillabel.setBounds(25, 155, 122, 25);

        senderaddresslabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        senderaddresslabel.setText("Sender Address:");
        jPanel1.add(senderaddresslabel);
        senderaddresslabel.setBounds(20, 230, 122, 25);

        receiveraddresslabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        receiveraddresslabel.setText("Receiver Address:");
        jPanel1.add(receiveraddresslabel);
        receiveraddresslabel.setBounds(20, 270, 134, 25);

        Orderdetaillabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Orderdetaillabel.setText("Order Details:");
        jPanel1.add(Orderdetaillabel);
        Orderdetaillabel.setBounds(25, 14, 117, 25);

        returnbutton.setBackground(new java.awt.Color(244, 246, 248));
        returnbutton.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        returnbutton.setText("Return");
        jPanel1.add(returnbutton);
        returnbutton.setBounds(530, 330, 100, 32);

        receivercontactlabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        receivercontactlabel.setText("Receiver Contact:");
        jPanel1.add(receivercontactlabel);
        receivercontactlabel.setBounds(20, 190, 134, 25);

        receivercontacttextfield.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        receivercontacttextfield.setText("9876543210");
        receivercontacttextfield.setBorder(null);
        jPanel1.add(receivercontacttextfield);
        receivercontacttextfield.setBounds(170, 190, 280, 25);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(250, 190, 740, 380);

        searchbutton.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        searchbutton.setText("Search");
        jPanel2.add(searchbutton);
        searchbutton.setBounds(672, 104, 99, 46);

        sidebar.setBackground(new java.awt.Color(33, 38, 49));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N

        Dashboard.setBackground(new java.awt.Color(33, 38, 49));
        Dashboard.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard.setText("Dashboard");

        ManageUser.setBackground(new java.awt.Color(33, 38, 49));
        ManageUser.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        ManageUser.setForeground(new java.awt.Color(255, 255, 255));
        ManageUser.setText("Manage User");

        WorkLoad.setBackground(new java.awt.Color(33, 38, 49));
        WorkLoad.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        WorkLoad.setForeground(new java.awt.Color(255, 255, 255));
        WorkLoad.setText("Workload");

        ActiveOrders.setBackground(new java.awt.Color(33, 38, 49));
        ActiveOrders.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        ActiveOrders.setForeground(new java.awt.Color(255, 255, 255));
        ActiveOrders.setText("Active Orders");

        ManageOrders.setBackground(new java.awt.Color(216, 140, 81));
        ManageOrders.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        ManageOrders.setForeground(new java.awt.Color(255, 255, 255));
        ManageOrders.setText("Manage Order");

        AssignOrder.setBackground(new java.awt.Color(33, 38, 49));
        AssignOrder.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        AssignOrder.setForeground(new java.awt.Color(255, 255, 255));
        AssignOrder.setText("Assign Orders");

        MyProfile.setBackground(new java.awt.Color(33, 38, 49));
        MyProfile.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        MyProfile.setForeground(new java.awt.Color(255, 255, 255));
        MyProfile.setText("My Profile");

        logout.setBackground(new java.awt.Color(33, 38, 49));
        logout.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 51, 51));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        logout.setText("Logout");

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator1)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(ManageUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WorkLoad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ActiveOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ManageOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AssignOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MyProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(ManageUser, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WorkLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ActiveOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManageOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AssignOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(sidebar);
        sidebar.setBounds(0, 0, 180, 590);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1050, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TrackingIdtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrackingIdtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrackingIdtextfieldActionPerformed

    private void receiveremailtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveremailtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiveremailtextfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManagerOrderEdit().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActiveOrders;
    private javax.swing.JButton AssignOrder;
    private javax.swing.JButton Dashboard;
    private javax.swing.JButton ManageOrders;
    private javax.swing.JButton ManageUser;
    private javax.swing.JButton MyProfile;
    private javax.swing.JLabel Orderdetaillabel;
    private javax.swing.JLabel Rolelabel;
    private javax.swing.JTextField TrackingIdtextfield;
    private javax.swing.JButton WorkLoad;
    private javax.swing.JButton editbutton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel logo;
    private javax.swing.JButton logout;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel pfplabel;
    private javax.swing.JLabel receiveraddresslabel;
    private javax.swing.JTextField receiveraddresstextfield;
    private javax.swing.JLabel receivercontactlabel;
    private javax.swing.JTextField receivercontacttextfield;
    private javax.swing.JLabel receiveremaillabel;
    private javax.swing.JTextField receiveremailtextfield;
    private javax.swing.JLabel receivernamelabel;
    private javax.swing.JTextField receivernametextfield;
    private javax.swing.JButton returnbutton;
    private javax.swing.JButton savebutton;
    private javax.swing.JButton searchbutton;
    private javax.swing.JLabel senderaddresslabel;
    private javax.swing.JTextField senderaddresstextfield;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel toppanel;
    private javax.swing.JLabel totalcostlabel;
    private javax.swing.JLabel trackingIDlabel;
    private javax.swing.JTextField trackingidtextfield;
    // End of variables declaration//GEN-END:variables
// Example additions inside ManagerOrderEdit.java
public javax.swing.JButton getSearchbutton() { return searchbutton; }
public javax.swing.JButton getEditbutton() { return editbutton; }
public javax.swing.JButton getSavebutton() { return savebutton; }
public javax.swing.JButton getReturnbutton() { return returnbutton; }
public javax.swing.JTextField getTrackingIdtextfield() { return TrackingIdtextfield; }
public javax.swing.JTextField getReceivernametextfield() { return receivernametextfield; }
public javax.swing.JTextField getReceiveraddresstextfield() { return receiveraddresstextfield; }
public javax.swing.JTextField getReceiveremailtextfield() { return receiveremailtextfield; }
public javax.swing.JTextField getSenderaddresstextfield() { return senderaddresstextfield; }

// Sidebar getters
public javax.swing.JButton getDashboard() { return Dashboard; }
public javax.swing.JButton getManageOrders() { return ManageOrders; }
public javax.swing.JButton getActiveOrders() { return ActiveOrders; }
public javax.swing.JButton getAssignOrder() { return AssignOrder; }
public javax.swing.JButton getManageUser() { return ManageUser; }
public javax.swing.JButton getWorkLoad() { return WorkLoad; }
public javax.swing.JButton getMyProfile() { return MyProfile; }
public javax.swing.JButton getLogout() { return logout; }

public void addLogoutListener(java.awt.event.ActionListener listener) {
        logout.addActionListener(listener);
    }

public void addDashboardListener(java.awt.event.ActionListener listener) {
        Dashboard.addActionListener(listener);
    }

// =========================================================================
    // GETTERS, SETTERS, AND LOCKING LOGIC
    // =========================================================================

    public String getSearchInput() {
        return TrackingIdtextfield.getText().trim();
    }

    public void setOrderDetails(String name, String email, String contact, String senderAddr, String receiverAddr, String cost) {
        receivernametextfield.setText(name);
        receiveremailtextfield.setText(email);
        receivercontacttextfield.setText(contact);
        senderaddresstextfield.setText(senderAddr);
        receiveraddresstextfield.setText(receiverAddr);
        
        // Assuming jTextField7 is your Total Cost field! Update if you renamed it.
        jTextField7.setText(cost); 
    }

    public void setFormEditable(boolean isEditable) {
        // Only allow editing for the specific requested fields
        receivernametextfield.setEditable(isEditable);
        receivercontacttextfield.setEditable(isEditable);
        receiveraddresstextfield.setEditable(isEditable);
        jTextField7.setEditable(isEditable); // Total Cost
        
        // Never allow editing these from this page
        receiveremailtextfield.setEditable(false);
        senderaddresstextfield.setEditable(false);
        
        // Toggle buttons
        savebutton.setEnabled(isEditable);
        editbutton.setEnabled(!isEditable);
    }

    // Grab the updated data for the database
    public String getUpdatedName() { return receivernametextfield.getText().trim(); }
    public String getUpdatedContact() { return receivercontacttextfield.getText().trim(); }
    public String getUpdatedAddress() { return receiveraddresstextfield.getText().trim(); }
    public String getUpdatedCost() { return jTextField7.getText().trim(); }

    // =========================================================================
    // BUTTON LISTENERS
    // =========================================================================
    
    public void addSearchListener(java.awt.event.ActionListener listener) { searchbutton.addActionListener(listener); }
    public void addEditListener(java.awt.event.ActionListener listener) { editbutton.addActionListener(listener); }
    public void addSaveListener(java.awt.event.ActionListener listener) { savebutton.addActionListener(listener); }
    public void addReturnOrderListener(java.awt.event.ActionListener listener) { returnbutton.addActionListener(listener); }

}
