/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author User
 */
public class OTPBasedPasswordReset extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OTPBasedPasswordReset.class.getName());

    /**
     * Creates new form OTPBasedPasswordReset
     */
    public OTPBasedPasswordReset() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DokoLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ResetYourPasswordLabel = new javax.swing.JLabel();
        BestForSecuringLabel = new javax.swing.JLabel();
        termsandconditioncheckbox = new javax.swing.JCheckBox();
        Fullnametextfield = new javax.swing.JTextField();
        currentpasswordtextfield = new javax.swing.JTextField();
        newpasswordtextfield = new javax.swing.JTextField();
        confirmnewpasswordtextfield = new javax.swing.JTextField();
        fullnamelabel = new javax.swing.JLabel();
        currentpasswordlabel = new javax.swing.JLabel();
        newpasswordlabel = new javax.swing.JLabel();
        confirmnewpasswordlabel = new javax.swing.JLabel();
        changepasswordbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1050, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1050, 600));
        getContentPane().setLayout(null);

        DokoLabel.setFont(new java.awt.Font("Righteous", 0, 59)); // NOI18N
        DokoLabel.setForeground(new java.awt.Color(41, 51, 123));
        DokoLabel.setText("DOKO");
        DokoLabel.setPreferredSize(new java.awt.Dimension(120, 54));
        getContentPane().add(DokoLabel);
        DokoLabel.setBounds(10, 0, 210, 70);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1050, 600));
        jPanel1.setName(""); // NOI18N

        jPanel2.setBackground(new java.awt.Color(236, 236, 236));
        jPanel2.setPreferredSize(new java.awt.Dimension(565, 678));

        ResetYourPasswordLabel.setFont(new java.awt.Font("Righteous", 1, 30)); // NOI18N
        ResetYourPasswordLabel.setForeground(new java.awt.Color(41, 51, 123));
        ResetYourPasswordLabel.setText("Reset password");

        BestForSecuringLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        BestForSecuringLabel.setText("best for securing");

        termsandconditioncheckbox.setText("terms and conditions ");
        termsandconditioncheckbox.addActionListener(this::termsandconditioncheckboxActionPerformed);

        Fullnametextfield.setText("full name*\n");
        Fullnametextfield.addActionListener(this::FullnametextfieldActionPerformed);

        currentpasswordtextfield.setText("current password*");
        currentpasswordtextfield.addActionListener(this::currentpasswordtextfieldActionPerformed);

        newpasswordtextfield.setText("new password*");
        newpasswordtextfield.addActionListener(this::newpasswordtextfieldActionPerformed);

        confirmnewpasswordtextfield.setText("confirm new password*");

        fullnamelabel.setText("Full name");

        currentpasswordlabel.setText("Current password");

        newpasswordlabel.setText("New password");

        confirmnewpasswordlabel.setText("Confirm new password");

        changepasswordbutton.setBackground(new java.awt.Color(213, 173, 100));
        changepasswordbutton.setFont(new java.awt.Font("REM", 0, 18)); // NOI18N
        changepasswordbutton.setText("Change Password");
        changepasswordbutton.setPreferredSize(new java.awt.Dimension(82, 30));
        changepasswordbutton.addActionListener(this::changepasswordbuttonActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(ResetYourPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(BestForSecuringLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fullnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(currentpasswordlabel)
                                    .addComponent(newpasswordlabel))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 3, Short.MAX_VALUE)
                                .addComponent(confirmnewpasswordlabel)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentpasswordtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fullnametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newpasswordtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmnewpasswordtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(changepasswordbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(termsandconditioncheckbox)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(ResetYourPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BestForSecuringLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fullnametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullnamelabel))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentpasswordlabel)
                    .addComponent(currentpasswordtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newpasswordlabel)
                    .addComponent(newpasswordtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmnewpasswordlabel)
                    .addComponent(confirmnewpasswordtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(termsandconditioncheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changepasswordbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(299, 299, 299))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1050, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void termsandconditioncheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termsandconditioncheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_termsandconditioncheckboxActionPerformed

    private void FullnametextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullnametextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FullnametextfieldActionPerformed

    private void currentpasswordtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentpasswordtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentpasswordtextfieldActionPerformed

    private void newpasswordtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpasswordtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpasswordtextfieldActionPerformed

    private void changepasswordbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepasswordbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changepasswordbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OTPBasedPasswordReset().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BestForSecuringLabel;
    private javax.swing.JLabel DokoLabel;
    private javax.swing.JTextField Fullnametextfield;
    private javax.swing.JLabel ResetYourPasswordLabel;
    private javax.swing.JButton changepasswordbutton;
    private javax.swing.JLabel confirmnewpasswordlabel;
    private javax.swing.JTextField confirmnewpasswordtextfield;
    private javax.swing.JLabel currentpasswordlabel;
    private javax.swing.JTextField currentpasswordtextfield;
    private javax.swing.JLabel fullnamelabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel newpasswordlabel;
    private javax.swing.JTextField newpasswordtextfield;
    private javax.swing.JCheckBox termsandconditioncheckbox;
    // End of variables declaration//GEN-END:variables
// =========================================================================
    // EXPOSE UI DATA AND BUTTONS TO THE CONTROLLER
    // =========================================================================

    public String getCurrentPassword() {
        return currentpasswordtextfield.getText();
    }

    public String getNewPassword() {
        return newpasswordtextfield.getText();
    }

    public String getConfirmNewPassword() {
        return confirmnewpasswordtextfield.getText();
    }

    public boolean isTermsAccepted() {
        return termsandconditioncheckbox.isSelected();
    }

    public void setFullName(String name) {
        Fullnametextfield.setText(name);
        Fullnametextfield.setEditable(false); // Lock it so they can't change it here
    }

    public void addChangePasswordListener(java.awt.event.ActionListener listener) {
        // Ensure 'changepasswordbutton' matches your variable name!
        changepasswordbutton.addActionListener(listener); 
    }

}
