/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author User
 */
public class OTPBasedPasswordReset extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OTPBasedPasswordReset.class.getName());

    /**
     * Creates new form OTPBasedPasswordReset
     */
    public OTPBasedPasswordReset() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DokoLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ResetYourPasswordLabel = new javax.swing.JLabel();
        BestForSecuringLabel = new javax.swing.JLabel();
        FullNameTextfield = new javax.swing.JTextField();
        CurrentPasswordTextfield = new javax.swing.JTextField();
        NewPasswordTextfield = new javax.swing.JTextField();
        ConfirmNewPasswordTextfield = new javax.swing.JTextField();
        ChangePasswordButton = new javax.swing.JButton();
        termsandconditioncheckbox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1500, 850));
        getContentPane().setLayout(null);

        DokoLabel.setFont(new java.awt.Font("Segoe UI", 0, 59)); // NOI18N
        DokoLabel.setForeground(new java.awt.Color(41, 51, 123));
        DokoLabel.setText("DOKO");
        DokoLabel.setPreferredSize(new java.awt.Dimension(120, 54));
        getContentPane().add(DokoLabel);
        DokoLabel.setBounds(10, 0, 170, 70);

        jPanel2.setBackground(new java.awt.Color(236, 236, 236));
        jPanel2.setPreferredSize(new java.awt.Dimension(565, 678));

        ResetYourPasswordLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        ResetYourPasswordLabel.setForeground(new java.awt.Color(41, 51, 123));
        ResetYourPasswordLabel.setText("Reset password");

        BestForSecuringLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        BestForSecuringLabel.setText("best for securing");

        FullNameTextfield.setBackground(new java.awt.Color(217, 217, 217));
        FullNameTextfield.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        FullNameTextfield.setForeground(new java.awt.Color(130, 130, 130));
        FullNameTextfield.setText("full name");
        FullNameTextfield.setPreferredSize(new java.awt.Dimension(444, 64));
        FullNameTextfield.addActionListener(this::FullNameTextfieldActionPerformed);

        CurrentPasswordTextfield.setBackground(new java.awt.Color(217, 217, 217));
        CurrentPasswordTextfield.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        CurrentPasswordTextfield.setForeground(new java.awt.Color(130, 130, 130));
        CurrentPasswordTextfield.setText("current password");
        CurrentPasswordTextfield.setPreferredSize(new java.awt.Dimension(444, 64));
        CurrentPasswordTextfield.addActionListener(this::CurrentPasswordTextfieldActionPerformed);

        NewPasswordTextfield.setBackground(new java.awt.Color(217, 217, 217));
        NewPasswordTextfield.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        NewPasswordTextfield.setForeground(new java.awt.Color(130, 130, 130));
        NewPasswordTextfield.setText("new password");
        NewPasswordTextfield.setPreferredSize(new java.awt.Dimension(444, 64));
        NewPasswordTextfield.addActionListener(this::NewPasswordTextfieldActionPerformed);

        ConfirmNewPasswordTextfield.setBackground(new java.awt.Color(217, 217, 217));
        ConfirmNewPasswordTextfield.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmNewPasswordTextfield.setForeground(new java.awt.Color(130, 130, 130));
        ConfirmNewPasswordTextfield.setText("confirm new password");
        ConfirmNewPasswordTextfield.setPreferredSize(new java.awt.Dimension(444, 64));

        ChangePasswordButton.setBackground(new java.awt.Color(213, 173, 100));
        ChangePasswordButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ChangePasswordButton.setText("Change Password");
        ChangePasswordButton.setPreferredSize(new java.awt.Dimension(295, 59));
        ChangePasswordButton.addActionListener(this::ChangePasswordButtonActionPerformed);

        termsandconditioncheckbox.setText("terms and conditions ");
        termsandconditioncheckbox.addActionListener(this::termsandconditioncheckboxActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(ChangePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CurrentPasswordTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FullNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewPasswordTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConfirmNewPasswordTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(termsandconditioncheckbox))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(ResetYourPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(BestForSecuringLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(ResetYourPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BestForSecuringLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(FullNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(CurrentPasswordTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewPasswordTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConfirmNewPasswordTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(termsandconditioncheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ChangePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(300, 60, 450, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FullNameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullNameTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FullNameTextfieldActionPerformed

    private void CurrentPasswordTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentPasswordTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrentPasswordTextfieldActionPerformed

    private void ChangePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePasswordButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangePasswordButtonActionPerformed

    private void NewPasswordTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPasswordTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewPasswordTextfieldActionPerformed

    private void termsandconditioncheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termsandconditioncheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_termsandconditioncheckboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OTPBasedPasswordReset().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BestForSecuringLabel;
    private javax.swing.JButton ChangePasswordButton;
    private javax.swing.JTextField ConfirmNewPasswordTextfield;
    private javax.swing.JTextField CurrentPasswordTextfield;
    private javax.swing.JLabel DokoLabel;
    private javax.swing.JTextField FullNameTextfield;
    private javax.swing.JTextField NewPasswordTextfield;
    private javax.swing.JLabel ResetYourPasswordLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox termsandconditioncheckbox;
    // End of variables declaration//GEN-END:variables
}
