/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Acer
 */
public class Sender_Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Sender_Dashboard.class.getName());

    /**
     * Creates new form Sender_Dashboard
     */
    public Sender_Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Dashboard = new javax.swing.JButton();
        MyShipments = new javax.swing.JButton();
        create_orders = new javax.swing.JButton();
        OrdersHistory = new javax.swing.JButton();
        MyProfile = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        logout = new javax.swing.JButton();
        topbar = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        user_role = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RecentOrders = new javax.swing.JTable();
        Total_orders = new javax.swing.JPanel();
        total_orders_text = new javax.swing.JLabel();
        total_orders_value = new javax.swing.JLabel();
        Cancel_Orders = new javax.swing.JPanel();
        Cancel_orders_text = new javax.swing.JLabel();
        Cancel_orders_value = new javax.swing.JLabel();
        Pending_shipments = new javax.swing.JPanel();
        Pending_shipments_text = new javax.swing.JLabel();
        Pending_shipments_value = new javax.swing.JLabel();
        Delivered_shipments = new javax.swing.JPanel();
        Deliverd_shipments_text = new javax.swing.JLabel();
        Deliverd_shipments_value = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(238, 233, 223));
        MainPanel.setPreferredSize(new java.awt.Dimension(1050, 600));
        MainPanel.setLayout(null);

        sidebar.setBackground(new java.awt.Color(33, 38, 49));
        sidebar.setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        sidebar.add(logo);
        logo.setBounds(0, 0, 176, 61);
        sidebar.add(jSeparator1);
        jSeparator1.setBounds(0, 67, 179, 10);

        Dashboard.setBackground(new java.awt.Color(216, 140, 81));
        Dashboard.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard.setText("Dashboard");
        Dashboard.addActionListener(this::DashboardActionPerformed);
        sidebar.add(Dashboard);
        Dashboard.setBounds(6, 83, 170, 55);

        MyShipments.setBackground(new java.awt.Color(33, 38, 49));
        MyShipments.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        MyShipments.setForeground(new java.awt.Color(255, 255, 255));
        MyShipments.setText("My Shipments");
        sidebar.add(MyShipments);
        MyShipments.setBounds(6, 217, 170, 55);

        create_orders.setBackground(new java.awt.Color(33, 38, 49));
        create_orders.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        create_orders.setForeground(new java.awt.Color(255, 255, 255));
        create_orders.setText("Create Order");
        sidebar.add(create_orders);
        create_orders.setBounds(6, 150, 170, 55);

        OrdersHistory.setBackground(new java.awt.Color(33, 38, 49));
        OrdersHistory.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        OrdersHistory.setForeground(new java.awt.Color(255, 255, 255));
        OrdersHistory.setText("Orders History");
        sidebar.add(OrdersHistory);
        OrdersHistory.setBounds(6, 284, 170, 55);

        MyProfile.setBackground(new java.awt.Color(33, 38, 49));
        MyProfile.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        MyProfile.setForeground(new java.awt.Color(255, 255, 255));
        MyProfile.setText("My Profile");
        sidebar.add(MyProfile);
        MyProfile.setBounds(6, 351, 170, 55);
        sidebar.add(jSeparator2);
        jSeparator2.setBounds(2, 530, 180, 3);

        logout.setBackground(new java.awt.Color(33, 38, 49));
        logout.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 102, 102));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(this::logoutActionPerformed);
        sidebar.add(logout);
        logout.setBounds(10, 540, 158, 45);

        MainPanel.add(sidebar);
        sidebar.setBounds(-1, 0, 180, 600);

        topbar.setLayout(null);

        username.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        username.setText("Name");
        topbar.add(username);
        username.setBounds(770, 20, 100, 22);

        user_role.setText("Role");
        topbar.add(user_role);
        user_role.setBounds(770, 40, 37, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pfp.jpg"))); // NOI18N
        topbar.add(jLabel3);
        jLabel3.setBounds(700, 5, 60, 60);

        MainPanel.add(topbar);
        topbar.setBounds(180, 0, 860, 70);

        RecentOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Recent Orders", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(RecentOrders);

        MainPanel.add(jScrollPane1);
        jScrollPane1.setBounds(263, 300, 710, 250);

        Total_orders.setLayout(null);

        total_orders_text.setBackground(new java.awt.Color(238, 238, 238));
        total_orders_text.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        total_orders_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_orders_text.setText("Total Orders");
        total_orders_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Total_orders.add(total_orders_text);
        total_orders_text.setBounds(0, 0, 140, 60);

        total_orders_value.setBackground(new java.awt.Color(238, 238, 238));
        total_orders_value.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        total_orders_value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_orders_value.setText("0");
        total_orders_value.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Total_orders.add(total_orders_value);
        total_orders_value.setBounds(140, 0, 50, 60);

        MainPanel.add(Total_orders);
        Total_orders.setBounds(250, 120, 190, 60);

        Cancel_Orders.setLayout(null);

        Cancel_orders_text.setBackground(new java.awt.Color(238, 238, 238));
        Cancel_orders_text.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cancel_orders_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cancel_orders_text.setText("Cancel Orders");
        Cancel_orders_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Cancel_Orders.add(Cancel_orders_text);
        Cancel_orders_text.setBounds(0, 0, 140, 60);

        Cancel_orders_value.setBackground(new java.awt.Color(238, 238, 238));
        Cancel_orders_value.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cancel_orders_value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cancel_orders_value.setText("0");
        Cancel_orders_value.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Cancel_Orders.add(Cancel_orders_value);
        Cancel_orders_value.setBounds(140, 0, 50, 60);

        MainPanel.add(Cancel_Orders);
        Cancel_Orders.setBounds(550, 120, 190, 60);

        Pending_shipments.setLayout(null);

        Pending_shipments_text.setBackground(new java.awt.Color(238, 238, 238));
        Pending_shipments_text.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Pending_shipments_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pending_shipments_text.setText("Pending_shipments");
        Pending_shipments_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Pending_shipments.add(Pending_shipments_text);
        Pending_shipments_text.setBounds(0, 0, 140, 60);

        Pending_shipments_value.setBackground(new java.awt.Color(238, 238, 238));
        Pending_shipments_value.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Pending_shipments_value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pending_shipments_value.setText("0");
        Pending_shipments_value.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Pending_shipments.add(Pending_shipments_value);
        Pending_shipments_value.setBounds(140, 0, 50, 60);

        MainPanel.add(Pending_shipments);
        Pending_shipments.setBounds(250, 210, 190, 60);

        Delivered_shipments.setLayout(null);

        Deliverd_shipments_text.setBackground(new java.awt.Color(238, 238, 238));
        Deliverd_shipments_text.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Deliverd_shipments_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Deliverd_shipments_text.setText("Cancel Orders");
        Deliverd_shipments_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Delivered_shipments.add(Deliverd_shipments_text);
        Deliverd_shipments_text.setBounds(0, 0, 140, 60);

        Deliverd_shipments_value.setBackground(new java.awt.Color(238, 238, 238));
        Deliverd_shipments_value.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Deliverd_shipments_value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Deliverd_shipments_value.setText("0");
        Deliverd_shipments_value.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Delivered_shipments.add(Deliverd_shipments_value);
        Deliverd_shipments_value.setBounds(140, 0, 50, 60);

        MainPanel.add(Delivered_shipments);
        Delivered_shipments.setBounds(550, 210, 190, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DashboardActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Sender_Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cancel_Orders;
    private javax.swing.JLabel Cancel_orders_text;
    private javax.swing.JLabel Cancel_orders_value;
    private javax.swing.JButton Dashboard;
    private javax.swing.JLabel Deliverd_shipments_text;
    private javax.swing.JLabel Deliverd_shipments_value;
    private javax.swing.JPanel Delivered_shipments;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton MyProfile;
    private javax.swing.JButton MyShipments;
    private javax.swing.JButton OrdersHistory;
    private javax.swing.JPanel Pending_shipments;
    private javax.swing.JLabel Pending_shipments_text;
    private javax.swing.JLabel Pending_shipments_value;
    private javax.swing.JTable RecentOrders;
    private javax.swing.JPanel Total_orders;
    private javax.swing.JButton create_orders;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo;
    private javax.swing.JButton logout;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel topbar;
    private javax.swing.JLabel total_orders_text;
    private javax.swing.JLabel total_orders_value;
    private javax.swing.JLabel user_role;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
public void setUsernameLabel(String name) {
        username.setText(name); // Replace 'username' with your actual JLabel variable
    }

    public void setRoleLabel(String role) {
        user_role.setText(role); // Replace 'user_role' with your actual JLabel variable
    }

    public void addLogoutListener(java.awt.event.ActionListener listener) {
        logout.addActionListener(listener); // Replace 'logoutBtn' with your actual JButton variable
    }

    public void addMyProfileListener(java.awt.event.ActionListener listener) {
        MyProfile.addActionListener(listener); 
    }
    public void addCreateOrderListener(java.awt.event.ActionListener listener) {
        create_orders.addActionListener(listener); 
    }
    // Add to the bottom of Sender_Dashboard.java
    public void addMyShipmentsListener(java.awt.event.ActionListener listener) {
        // NOTE: Ensure 'MyShipments' is the exact variable name of your button!
        MyShipments.addActionListener(listener); 
    }
    public void addBackToShipmentsListener(java.awt.event.ActionListener listenForBackButton) {
        
        // CHANGE 'btnBack' to whatever variable name you gave your actual button!
        MyShipments.addActionListener(listenForBackButton); 
        
    }
    // Add to the bottom of Sender_Dashboard.java
    public void addOrdersHistoryListener(java.awt.event.ActionListener listener) {
        // Ensure 'OrdersHistory' perfectly matches the variable name of your button!
        OrdersHistory.addActionListener(listener); 
    }
}
