/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author parbatshrestha
 */
public class Useraccountmanagement extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Useraccountmanagement.class.getName());


    public Useraccountmanagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dashboard1 = new javax.swing.JButton();
        MainPanel1 = new javax.swing.JPanel();
        sidebar1 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        ManageUser1 = new javax.swing.JButton();
        WorkLoad1 = new javax.swing.JButton();
        ActiveOrders1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        AssignOrder1 = new javax.swing.JButton();
        MyProfile1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        logout1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        dashboard = new javax.swing.JButton();
        edit_of_email_and_number_panel = new javax.swing.JPanel();
        employee_ID = new javax.swing.JLabel();
        employee_details = new javax.swing.JLabel();
        Employee_Name = new javax.swing.JLabel();
        Employee_Email = new javax.swing.JLabel();
        Employee_Phone = new javax.swing.JLabel();
        Employee_Email_value = new javax.swing.JLabel();
        Employee_ID_value = new javax.swing.JLabel();
        Employee_Name_value = new javax.swing.JLabel();
        Employee_Phone_value = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        entered_user_id = new javax.swing.JTextField();
        search_id = new javax.swing.JButton();
        top_bar_panel = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        user_role = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();

        Dashboard1.setBackground(new java.awt.Color(33, 38, 49));
        Dashboard1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        Dashboard1.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard1.setText("Dashboard");
        Dashboard1.addActionListener(this::Dashboard1ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel1.setBackground(new java.awt.Color(238, 233, 223));
        MainPanel1.setPreferredSize(new java.awt.Dimension(1050, 600));
        MainPanel1.setLayout(null);

        sidebar1.setBackground(new java.awt.Color(33, 38, 49));

        ManageUser1.setBackground(new java.awt.Color(216, 140, 81));
        ManageUser1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        ManageUser1.setForeground(new java.awt.Color(255, 255, 255));
        ManageUser1.setText("Manage User");

        WorkLoad1.setBackground(new java.awt.Color(33, 38, 49));
        WorkLoad1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        WorkLoad1.setForeground(new java.awt.Color(255, 255, 255));
        WorkLoad1.setText("Workload");

        ActiveOrders1.setBackground(new java.awt.Color(33, 38, 49));
        ActiveOrders1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        ActiveOrders1.setForeground(new java.awt.Color(255, 255, 255));
        ActiveOrders1.setText("Active Orders");

        jButton11.setBackground(new java.awt.Color(33, 38, 49));
        jButton11.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Manage Order");

        AssignOrder1.setBackground(new java.awt.Color(33, 38, 49));
        AssignOrder1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        AssignOrder1.setForeground(new java.awt.Color(255, 255, 255));
        AssignOrder1.setText("Assign Orders");

        MyProfile1.setBackground(new java.awt.Color(33, 38, 49));
        MyProfile1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        MyProfile1.setForeground(new java.awt.Color(255, 255, 255));
        MyProfile1.setText("My Profile");

        logout1.setBackground(new java.awt.Color(33, 38, 49));
        logout1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        logout1.setForeground(new java.awt.Color(255, 51, 51));
        logout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        logout1.setText("Logout");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N

        dashboard.setBackground(new java.awt.Color(33, 38, 49));
        dashboard.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setText("Dashboard");

        javax.swing.GroupLayout sidebar1Layout = new javax.swing.GroupLayout(sidebar1);
        sidebar1.setLayout(sidebar1Layout);
        sidebar1Layout.setHorizontalGroup(
            sidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addComponent(jSeparator3)
            .addGroup(sidebar1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addGroup(sidebar1Layout.createSequentialGroup()
                        .addComponent(logout1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebar1Layout.createSequentialGroup()
                        .addGroup(sidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MyProfile1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AssignOrder1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ActiveOrders1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(WorkLoad1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ManageUser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        sidebar1Layout.setVerticalGroup(
            sidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManageUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WorkLoad1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ActiveOrders1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AssignOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MyProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logout1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        MainPanel1.add(sidebar1);
        sidebar1.setBounds(0, 0, 180, 644);

        edit_of_email_and_number_panel.setBackground(new java.awt.Color(255, 255, 255));
        edit_of_email_and_number_panel.setLayout(null);

        employee_ID.setText("Employee ID");
        edit_of_email_and_number_panel.add(employee_ID);
        employee_ID.setBounds(26, 93, 100, 32);

        employee_details.setText("Employee Details");
        edit_of_email_and_number_panel.add(employee_details);
        employee_details.setBounds(30, 29, 160, 32);

        Employee_Name.setText("Employee Name");
        edit_of_email_and_number_panel.add(Employee_Name);
        Employee_Name.setBounds(26, 131, 100, 35);

        Employee_Email.setText("Employee Email");
        edit_of_email_and_number_panel.add(Employee_Email);
        Employee_Email.setBounds(26, 172, 100, 35);

        Employee_Phone.setText("Phone Number");
        edit_of_email_and_number_panel.add(Employee_Phone);
        Employee_Phone.setBounds(26, 213, 90, 35);

        Employee_Email_value.setText(": ram@gmail.com");
        edit_of_email_and_number_panel.add(Employee_Email_value);
        Employee_Email_value.setBounds(139, 173, 270, 32);

        Employee_ID_value.setText(": #11111");
        edit_of_email_and_number_panel.add(Employee_ID_value);
        Employee_ID_value.setBounds(139, 93, 210, 32);

        Employee_Name_value.setText(": Ram");
        edit_of_email_and_number_panel.add(Employee_Name_value);
        Employee_Name_value.setBounds(139, 134, 230, 32);

        Employee_Phone_value.setText(": 980000000000");
        edit_of_email_and_number_panel.add(Employee_Phone_value);
        Employee_Phone_value.setBounds(139, 213, 280, 32);

        editBtn.setBackground(new java.awt.Color(242, 242, 242));
        editBtn.setText("Edit");
        edit_of_email_and_number_panel.add(editBtn);
        editBtn.setBounds(599, 30, 72, 31);

        savebtn.setBackground(new java.awt.Color(242, 242, 242));
        savebtn.setText("Save");
        savebtn.addActionListener(this::savebtnActionPerformed);
        edit_of_email_and_number_panel.add(savebtn);
        savebtn.setBounds(599, 266, 72, 31);

        MainPanel1.add(edit_of_email_and_number_panel);
        edit_of_email_and_number_panel.setBounds(250, 180, 694, 342);

        entered_user_id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        entered_user_id.setText("# Enter User ID");
        entered_user_id.addActionListener(this::entered_user_idActionPerformed);
        MainPanel1.add(entered_user_id);
        entered_user_id.setBounds(240, 120, 350, 31);

        search_id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        search_id.setText("Search");
        search_id.addActionListener(this::search_idActionPerformed);
        MainPanel1.add(search_id);
        search_id.setBounds(600, 120, 100, 30);

        top_bar_panel.setLayout(null);

        username.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        username.setText("Name");
        top_bar_panel.add(username);
        username.setBounds(770, 20, 100, 22);

        user_role.setText("Role");
        top_bar_panel.add(user_role);
        user_role.setBounds(770, 40, 100, 16);

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pfp.jpg"))); // NOI18N
        top_bar_panel.add(profile);
        profile.setBounds(700, 5, 60, 60);

        MainPanel1.add(top_bar_panel);
        top_bar_panel.setBounds(180, 0, 870, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savebtnActionPerformed

    private void entered_user_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entered_user_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entered_user_idActionPerformed

    private void search_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_idActionPerformed

    private void Dashboard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dashboard1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dashboard1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Useraccountmanagement().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActiveOrders1;
    private javax.swing.JButton AssignOrder1;
    private javax.swing.JButton Dashboard1;
    private javax.swing.JLabel Employee_Email;
    private javax.swing.JLabel Employee_Email_value;
    private javax.swing.JLabel Employee_ID_value;
    private javax.swing.JLabel Employee_Name;
    private javax.swing.JLabel Employee_Name_value;
    private javax.swing.JLabel Employee_Phone;
    private javax.swing.JLabel Employee_Phone_value;
    private javax.swing.JPanel MainPanel1;
    private javax.swing.JButton ManageUser1;
    private javax.swing.JButton MyProfile1;
    private javax.swing.JButton WorkLoad1;
    private javax.swing.JButton dashboard;
    private javax.swing.JButton editBtn;
    private javax.swing.JPanel edit_of_email_and_number_panel;
    private javax.swing.JLabel employee_ID;
    private javax.swing.JLabel employee_details;
    private javax.swing.JTextField entered_user_id;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton logout1;
    private javax.swing.JLabel profile;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton search_id;
    private javax.swing.JPanel sidebar1;
    private javax.swing.JPanel top_bar_panel;
    private javax.swing.JLabel user_role;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
// =========================================================================
    // GETTERS AND SETTERS FOR UI COMPONENTS
    // =========================================================================

    public void setUsernameLabel(String name) { username.setText(name); }
    public void setRoleLabel(String role) { user_role.setText(role); }

    // Grabs the text typed into your new search box
    public String getSearchId() {
        return entered_user_id.getText().trim();
    }

    // Injects data into the display labels
    public void setEmployeeDetails(String id, String name, String email, String phone) {
        Employee_ID_value.setText(id);
        Employee_Name_value.setText(name);
        Employee_Email_value.setText(email);
        Employee_Phone_value.setText(phone);
    }
    
    // Grabs the text currently sitting in the labels
    public String getDisplayedEmail() { return Employee_Email_value.getText(); }
    public String getDisplayedPhone() { return Employee_Phone_value.getText(); }

    // =========================================================================
    // BUTTON LISTENERS (Using your updated '1' variables)
    // =========================================================================

    public void addSearchListener(java.awt.event.ActionListener listener) {
        search_id.addActionListener(listener);
    }

    public void addEditListener(java.awt.event.ActionListener listener) {
        editBtn.addActionListener(listener);
    }

    public void addSaveListener(java.awt.event.ActionListener listener) {
        savebtn.addActionListener(listener);
    }
    
    public void addDashboardListener(java.awt.event.ActionListener listener) {
        Dashboard1.addActionListener(listener); 
    }
}
